In [1]:
from pathlib import Path
import json
import re
import warnings

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

# ============================================================
# 1. Base paths
# ============================================================
BASE_DIR = Path("../data")

MIRAGE_DIR = BASE_DIR / "MiRAGE"
PRIMEKG_DIR = BASE_DIR / "kg"

# MiRAGE / Kaggle drug repositioning files
MIRAGE_MAPPING_PATH = MIRAGE_DIR / "mapping.csv"
MIRAGE_DRUGINFO_PATH = MIRAGE_DIR / "drugsinfo.csv"
MIRAGE_DISEASEINFO_PATH = MIRAGE_DIR / "diseasesinfo.csv"

# PrimeKG files
PRIMEKG_NODES_PATH = PRIMEKG_DIR / "node.csv"
PRIMEKG_KG_PATH = PRIMEKG_DIR / "kg.csv"
PRIMEKG_EDGES_PATH = PRIMEKG_DIR / "edges.csv"
PRIMEKG_KG_DIRECTED_PATH = PRIMEKG_DIR / "kg_directed.csv"

# MONDO ontology file used for MeSH -> MONDO disease mapping
MONDO_JSON_PATH = MIRAGE_DIR / "mondo.json"

# Output directory
OUTPUT_DIR = BASE_DIR / "processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================
# 2. LLM training source paths
# ============================================================
# LLM 训练材料来自 RepoDB 和 DrugRepoBank 的原始 drug-disease pairs。
# 后续将用 DrugBank ID + disease name 文本标准化，从 MiRAGE 外部测试集中
# 剔除与这些训练来源重复的关系。
REPODB_RAW_PATH = BASE_DIR / "repodb/repodb.csv"
DRUGREPOBANK_RAW_PATH = BASE_DIR / "drugrepobank/drugrepobank.csv"

# 是否启用 raw source overlap 过滤。
USE_RAW_TRAIN_SOURCE_OVERLAP_FILTER = True

# ============================================================
# 3. PrimeKG relation settings
# ============================================================
# MiRAGE 是 positive-only 外部数据。
# 为避免测试泄漏，凡是 MiRAGE pair 已经出现在 PrimeKG 的 drug-disease
# therapeutic/safety relations 中，就从 external test 中剔除。
PRIMEKG_DD_RELATIONS = {
    "indication",
    "off-label use",
    "contraindication",
    "rev_indication",
    "rev_off-label use",
    "rev_contraindication",
}

# MiRAGE positive-only pair 转成 TxGNN external positive edge 时使用的默认关系。
DEFAULT_EXTERNAL_RELATION = "indication"

# Reproducibility
SEED = 42

print("Configuration loaded.")
print(f"BASE_DIR: {BASE_DIR.resolve()}")
print(f"MIRAGE_DIR: {MIRAGE_DIR.resolve()}")
print(f"PRIMEKG_DIR: {PRIMEKG_DIR.resolve()}")
print(f"OUTPUT_DIR: {OUTPUT_DIR.resolve()}")
print(f"RepoDB raw path: {REPODB_RAW_PATH.resolve()}")
print(f"DrugRepoBank raw path: {DRUGREPOBANK_RAW_PATH.resolve()}")

Configuration loaded.
BASE_DIR: D:\PycharmProjects\TxGNN\data
MIRAGE_DIR: D:\PycharmProjects\TxGNN\data\MiRAGE
PRIMEKG_DIR: D:\PycharmProjects\TxGNN\data\kg
OUTPUT_DIR: D:\PycharmProjects\TxGNN\data\processed
RepoDB raw path: D:\PycharmProjects\TxGNN\data\repodb\repodb.csv
DrugRepoBank raw path: D:\PycharmProjects\TxGNN\data\drugrepobank\drugrepobank.csv

In [2]:
# ============================================================
# 2. Utility functions: ID normalization, text normalization,
#    robust CSV reading, and encoding test
# ============================================================

def normalize_id(x):
    """
    Normalize general string IDs.
    Handles NaN, extra spaces, and pandas-read numeric artifacts like '123.0'.
    """
    if pd.isna(x):
        return pd.NA

    s = str(x).strip()
    if s == "":
        return pd.NA

    # Avoid turning IDs like DB00123 into numbers.
    # Only normalize pure numeric strings such as '123.0'.
    try:
        f = float(s)
        if f.is_integer() and re.fullmatch(r"\d+(\.0+)?", s):
            return str(int(f))
    except Exception:
        pass

    return s


def canonical_drugbank_id(x):
    """
    Normalize DrugBank IDs.
    Example: ' db00123 ' -> 'DB00123'
    """
    s = normalize_id(x)
    if pd.isna(s):
        return pd.NA
    return str(s).strip().upper()


def canonical_mesh_id(x, with_prefix=True):
    """
    Normalize MeSH disease IDs.

    Examples:
        'MESH:D000013' -> 'MESH:D000013' if with_prefix=True
        'D13'          -> 'MESH:D000013'
        '000013'       -> 'MESH:D000013'
        'D000013'      -> 'D000013' if with_prefix=False
    """
    if pd.isna(x):
        return pd.NA

    s = str(x).strip()
    if s == "":
        return pd.NA

    s = s.replace("MESH:", "")
    s = s.split("/")[-1]

    if s.startswith("D"):
        num = s[1:]
    else:
        num = s

    num = re.sub(r"\D", "", num)
    if num == "":
        return pd.NA

    mesh = "D" + num.zfill(6)
    return "MESH:" + mesh if with_prefix else mesh


def normalize_primekg_node_id(x):
    """
    Normalize PrimeKG node_id.

    PrimeKG disease MONDO node IDs in your earlier notebook appear as numeric strings
    with prefixes and leading zeros removed. This function standardizes:
        'MONDO:0001234' -> '1234'
        'MONDO_0001234' -> '1234'
        '1234.0'        -> '1234'
    DrugBank IDs such as DB00001 are preserved.
    """
    s = normalize_id(x)
    if pd.isna(s):
        return pd.NA

    s = str(s).strip()

    if s.startswith("MONDO:"):
        s = s.replace("MONDO:", "")
    if s.startswith("MONDO_"):
        s = s.replace("MONDO_", "")

    if re.fullmatch(r"\d+(\.0+)?", s):
        return str(int(float(s)))

    return s


def normalize_text(x):
    """
    Normalize text for conservative name-level overlap matching.
    """
    if pd.isna(x):
        return ""
    s = str(x).strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def safe_read_csv(path, encodings=("utf-8", "utf-8-sig", "cp1252", "latin1", "gb18030"), **kwargs):
    """
    Try reading a CSV using multiple common encodings.
    Returns:
        df, encoding_used
    """
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    last_error = None
    for enc in encodings:
        try:
            df = pd.read_csv(path, encoding=enc, **kwargs)
            return df, enc
        except Exception as e:
            last_error = e

    raise RuntimeError(f"Failed to read {path} with encodings={encodings}. Last error: {last_error}")


def try_read_csv_encodings(path, encodings=("utf-8", "utf-8-sig", "cp1252", "latin1", "gb18030"), nrows=5):
    """
    Print which encodings can read the CSV. Useful for files like DrugRepoBank.
    """
    path = Path(path)
    print(f"Testing encodings for: {path}")
    print("=" * 100)

    results = []

    for enc in encodings:
        try:
            df_tmp = pd.read_csv(path, encoding=enc, nrows=nrows)
            print(f"[OK] encoding={enc}, shape={df_tmp.shape}")
            display(df_tmp.head(2))
            results.append((enc, "OK", None))
        except Exception as e:
            print(f"[FAIL] encoding={enc}: {type(e).__name__}: {e}")
            results.append((enc, "FAIL", str(e)))
        print("-" * 100)

    return results


def report_count(name, df):
    print(f"{name}: {len(df):,}")

In [3]:
# ============================================================
# 3. Load raw data
# ============================================================

# MiRAGE files
mapping_df, mapping_enc = safe_read_csv(MIRAGE_MAPPING_PATH)
drug_info, druginfo_enc = safe_read_csv(MIRAGE_DRUGINFO_PATH)
disease_info, diseaseinfo_enc = safe_read_csv(MIRAGE_DISEASEINFO_PATH)

# PrimeKG nodes
node_df, node_enc = safe_read_csv(PRIMEKG_NODES_PATH)

# LLM training source raw files
repodb_df, repodb_enc = safe_read_csv(REPODB_RAW_PATH)

# DrugRepoBank: known to contain non-UTF-8-compatible bytes; use cp1252.
drugrepobank_df = pd.read_csv(DRUGREPOBANK_RAW_PATH, encoding="cp1252")
drugrepobank_enc = "cp1252"

print("Loaded files and encodings:")
print(f"mapping.csv:       {mapping_enc}, shape={mapping_df.shape}")
print(f"druginfo.csv:      {druginfo_enc}, shape={drug_info.shape}")
print(f"diseaseinfo.csv:   {diseaseinfo_enc}, shape={disease_info.shape}")
print(f"PrimeKG nodes.csv: {node_enc}, shape={node_df.shape}")
print(f"repodb.csv:        {repodb_enc}, shape={repodb_df.shape}")
print(f"drugrepobank.csv:  {drugrepobank_enc}, shape={drugrepobank_df.shape}")

print("\nColumns:")
print("mapping_df:", mapping_df.columns.tolist())
print("drug_info:", drug_info.columns.tolist())
print("disease_info:", disease_info.columns.tolist())
print("node_df:", node_df.columns.tolist())
print("repodb_df:", repodb_df.columns.tolist())
print("drugrepobank_df:", drugrepobank_df.columns.tolist())

# ============================================================
# Required column checks
# ============================================================

required_mapping_cols = {"DrugID", "DiseaseID"}
required_druginfo_cols = {"DrugID"}
required_diseaseinfo_cols = {"DiseaseID"}
required_nodes_cols = {"node_index", "node_id", "node_type", "node_name"}

missing_mapping = required_mapping_cols - set(mapping_df.columns)
missing_drug_info = required_druginfo_cols - set(drug_info.columns)
missing_disease_info = required_diseaseinfo_cols - set(disease_info.columns)
missing_nodes = required_nodes_cols - set(node_df.columns)

assert not missing_mapping, f"mapping.csv missing columns: {missing_mapping}"
assert not missing_drug_info, f"druginfo.csv missing columns: {missing_drug_info}"
assert not missing_disease_info, f"diseaseinfo.csv missing columns: {missing_disease_info}"
assert not missing_nodes, f"PrimeKG nodes.csv missing columns: {missing_nodes}"

# RepoDB expected columns
required_repodb_cols = {"drugbank_id", "ind_name"}
missing_repodb = required_repodb_cols - set(repodb_df.columns)
assert not missing_repodb, f"repodb.csv missing columns: {missing_repodb}"

# DrugRepoBank expected columns
required_drb_cols = {"DrugID"}
missing_drb = required_drb_cols - set(drugrepobank_df.columns)
assert not missing_drb, f"drugrepobank.csv missing columns: {missing_drb}"

# ============================================================
# ID normalization
# ============================================================

# MiRAGE pair IDs
mapping_df["DrugID"] = mapping_df["DrugID"].apply(canonical_drugbank_id)
mapping_df["DiseaseID"] = mapping_df["DiseaseID"].apply(
    lambda x: canonical_mesh_id(x, with_prefix=True)
)

# MiRAGE text info IDs
drug_info["DrugID"] = drug_info["DrugID"].apply(canonical_drugbank_id)
disease_info["DiseaseID"] = disease_info["DiseaseID"].apply(
    lambda x: canonical_mesh_id(x, with_prefix=True)
)

# PrimeKG node IDs
node_df["node_id"] = node_df["node_id"].apply(normalize_primekg_node_id)
node_df["node_type"] = node_df["node_type"].astype(str)

# RepoDB IDs / names
repodb_df["drugbank_id"] = repodb_df["drugbank_id"].apply(canonical_drugbank_id)
repodb_df["ind_name_norm"] = repodb_df["ind_name"].apply(normalize_text)

# DrugRepoBank IDs
drugrepobank_df["DrugID"] = drugrepobank_df["DrugID"].apply(canonical_drugbank_id)

# Disease name fields in DrugRepoBank:
# - Disease: original disease/context
# - NewDisease: repositioning/new disease, likely more relevant
if "Disease" in drugrepobank_df.columns:
    drugrepobank_df["Disease_norm"] = drugrepobank_df["Disease"].apply(normalize_text)
else:
    drugrepobank_df["Disease_norm"] = ""

if "NewDisease" in drugrepobank_df.columns:
    drugrepobank_df["NewDisease_norm"] = drugrepobank_df["NewDisease"].apply(normalize_text)
else:
    drugrepobank_df["NewDisease_norm"] = ""

# ============================================================
# Basic summary
# ============================================================

print("\nBasic counts:")
report_count("MiRAGE mapping rows", mapping_df)
print("MiRAGE unique DrugID:", mapping_df["DrugID"].nunique())
print("MiRAGE unique DiseaseID:", mapping_df["DiseaseID"].nunique())

print("\nMiRAGE mapping head:")
display(mapping_df.head())

print("\nDrugRepoBank head:")
display(drugrepobank_df.head())

print("\nRepoDB head:")
display(repodb_df.head())

Loaded files and encodings:
mapping.csv:       utf-8, shape=(42200, 2)
druginfo.csv:      utf-8, shape=(1410, 9)
diseaseinfo.csv:   utf-8, shape=(1573, 5)
PrimeKG nodes.csv: utf-8, shape=(129375, 5)
repodb.csv:        utf-8, shape=(13558, 8)
drugrepobank.csv:  cp1252, shape=(169, 16)

Columns:
mapping_df: ['DrugID', 'DiseaseID']
drug_info: ['DrugID', 'DrugName', 'DrugDescription', 'DrugTarget', 'DrugPharmacodynamics', 'DrugSmile', 'DrugMechanism', 'DrugConditions', 'DrugCategories']
disease_info: ['DiseaseID', 'DiseaseName', 'DiseaseDescription', 'SlimMapping', 'PathwayNames']
node_df: ['node_index', 'node_id', 'node_type', 'node_name', 'node_source']
repodb_df: ['drug_name', 'drugbank_id', 'ind_name', 'ind_id', 'NCT', 'status', 'phase', 'DetailedStatus']
drugrepobank_df: ['DrugName', 'DrugID', 'PubChemID', 'Target', 'Disease', 'Side_effect', 'NewDirectTarget', 'NewIndirectTarget', 'NewDisease', 'Evidence', 'Insilico', 'Invitro', 'Invivo', 'Clinicaltrial', 'SupportedSentences', 'PMID']

Basic counts:
MiRAGE mapping rows: 42,200
MiRAGE unique DrugID: 1410
MiRAGE unique DiseaseID: 1573

MiRAGE mapping head:

    DrugID     DiseaseID
0  DB09140  MESH:D000013
1  DB00730  MESH:D000013
2  DB00898  MESH:D000013
3  DB01168  MESH:D000013
4  DB00550  MESH:D000013

DrugRepoBank head:

,DrugName,DrugID,PubChemID,Target,Disease,Side_effect,NewDirectTarget,NewIndirectTarget,NewDisease,Evidence,Insilico,Invitro,Invivo,Clinicaltrial,SupportedSentences,PMID,Disease_norm,NewDisease_norm
0,Spiramycin,DB06145,6440717.0,Gram-positive bacteria,Bacterial infection,NaN,NaN,LPS; iNOS; MAPKs; ERK; JNK; NF-?oB,Anti-inflammatory,Human skin primary irritation tests,NaN,Human skin primary irritation tests,NaN,NaN,Anti-Inflammatory Effects of Spiramycin in LPS...,35630676,bacterial infection,anti-inflammatory
1,Disulfiram,DB00822,3117.0,AL3A2,Alcohol dependence,NaN,NaN,metastasis related proteins (PCNA; MMP-2); Wnt...,Gastric cancer,Transwell assays; ELISA,NaN,Transwell assays; ELISA,NaN,NaN,The anti-alcohol dependency drug disulfiram in...,32529870,alcohol dependence,gastric cancer
2,Fluvoxamine,DB00176,3404.0,Serotonin system,Depression,NaN,NaN,A?242,Alzheimer's disease (AD),Aggregation kinetic experiments; transmission ...,NaN,Aggregation kinetic experiments; Transmission ...,NaN,NaN,These studies demonstrate that SSRIs have the ...,30157623,depression,alzheimer's disease (ad)
3,Paroxetine,DB00715,43815.0,SC6A4,Depression,NaN,NaN,A?242,Alzheimer's disease (AD),Aggregation kinetic experiments; transmission ...,NaN,Aggregation kinetic experiments; Transmission ...,NaN,NaN,These studies demonstrate that SSRIs have the ...,30157623,depression,alzheimer's disease (ad)
4,Fluoxetine,DB00472,3386.0,SC6A4,Depression,NaN,NaN,A?242,Alzheimer's disease (AD),Aggregation kinetic experiments; transmission ...,NaN,Aggregation kinetic experiments; Transmission ...,NaN,NaN,These studies demonstrate that SSRIs have the ...,30157623,depression,alzheimer's disease (ad)

RepoDB head:

,drug_name,drugbank_id,ind_name,ind_id,NCT,status,phase,DetailedStatus,ind_name_norm
0,ajmaline,DB01426,Ventricular arrhythmia,C0085612,NaN,Approved,NaN,NaN,ventricular arrhythmia
1,ajmaline,DB01426,Supraventricular arrhythmia,C0428974,NaN,Approved,NaN,NaN,supraventricular arrhythmia
2,ajmaline,DB01426,Cardiac Arrhythmia,C0003811,NaN,Approved,NaN,NaN,cardiac arrhythmia
3,emtricitabine,DB00879,HIV Infections,C0019693,NaN,Approved,NaN,NaN,hiv infections
4,enalapril,DB00584,Asymptomatic left ventricular systolic dysfunc...,C3698411,NaN,Approved,NaN,NaN,asymptomatic left ventricular systolic dysfunc...

In [4]:
# ============================================================
# 4. Merge MiRAGE mapping with drug/disease text information
# ============================================================

mirage = mapping_df.copy()

# MiRAGE 是 positive-only 数据集；如果原始 mapping.csv 没有 label，则统一补 label=1。
if "label" not in mirage.columns:
    mirage["label"] = 1

# 合并 drug text fields
mirage = mirage.merge(
    drug_info,
    on="DrugID",
    how="left",
    validate="many_to_one",
)

# 合并 disease text fields
mirage = mirage.merge(
    disease_info,
    on="DiseaseID",
    how="left",
    validate="many_to_one",
)

# 文本标准化列，后续用于和 RepoDB / DrugRepoBank 做 name-level overlap 过滤
mirage["DrugName_norm"] = mirage["DrugName"].apply(normalize_text)
mirage["DiseaseName_norm"] = mirage["DiseaseName"].apply(normalize_text)

# pair key: 用于 MiRAGE 内部去重和训练源 overlap 检查
mirage["drug_disease_name_key"] = list(
    zip(mirage["DrugID"], mirage["DiseaseName_norm"])
)

# ============================================================
# Basic quality checks
# ============================================================

print("MiRAGE with text info shape:", mirage.shape)

missing_drug_name = mirage["DrugName"].isna().sum()
missing_disease_name = mirage["DiseaseName"].isna().sum()

print(f"Missing DrugName rows: {missing_drug_name:,} ({missing_drug_name / len(mirage):.4%})")
print(f"Missing DiseaseName rows: {missing_disease_name:,} ({missing_disease_name / len(mirage):.4%})")

print("\nLabel distribution:")
print(mirage["label"].value_counts(dropna=False))

print("\nDuplicate DrugID-DiseaseID pairs:")
dup_count = mirage.duplicated(subset=["DrugID", "DiseaseID"]).sum()
print(f"Duplicated rows by DrugID-DiseaseID: {dup_count:,}")

print("\nMiRAGE merged head:")
display(mirage.head())

# Optional: if duplicate pairs exist, inspect them.
if dup_count > 0:
    print("\nExample duplicated pairs:")
    display(
        mirage[mirage.duplicated(subset=["DrugID", "DiseaseID"], keep=False)]
        .sort_values(["DrugID", "DiseaseID"])
        .head(10)
    )

MiRAGE with text info shape: (42200, 18)
Missing DrugName rows: 0 (0.0000%)
Missing DiseaseName rows: 0 (0.0000%)

Label distribution:
label
1    42200
Name: count, dtype: int64

Duplicate DrugID-DiseaseID pairs:
Duplicated rows by DrugID-DiseaseID: 0

MiRAGE merged head:

,DrugID,DiseaseID,label,DrugName,DrugDescription,DrugTarget,DrugPharmacodynamics,DrugSmile,DrugMechanism,DrugConditions,DrugCategories,DiseaseName,DiseaseDescription,SlimMapping,PathwayNames,DrugName_norm,DiseaseName_norm,drug_disease_name_key
0,DB09140,MESH:D000013,1,Oxygen,Oxygenis an essential element for human surviv...,"['P00395', 'Q9Y5S8']",Oxygen therapy improves effective cellular oxy...,O=O,Oxygen therapy increases the arterial pressure...,[],"['Chalcogens', 'Elements', 'Gases', 'Medical G...",Congenital Abnormalities,Malformations of organs or body parts during d...,['Congenital abnormality'],Vesicle-mediated transport,oxygen,congenital abnormalities,"(DB09140, congenital abnormalities)"
1,DB00730,MESH:D000013,1,Thiabendazole,Thiabendazoleis a benzimidazole used in the tr...,['P00363'],Thiabendazole is a fungicide and parasiticide....,N1C2=CC=CC=C2N=C1C1=CSC=N1,The precise mode of action of thiabendazole on...,[],"['Anthelmintics', 'Anti-Infective Agents', 'An...",Congenital Abnormalities,Malformations of organs or body parts during d...,['Congenital abnormality'],Vesicle-mediated transport,thiabendazole,congenital abnormalities,"(DB00730, congenital abnormalities)"
2,DB00898,MESH:D000013,1,Ethanol,"A clear, colorless liquid rapidly absorbed fro...","['P14867', 'Q8TCU5', 'P23415', 'P23416', 'Q026...",Alcohol produces injury to cells by dehydratio...,CCO,Ethanol affects the brain’s neurons in several...,"['Hand Hygiene', 'Skin disinfection']","['Agents Causing Muscle Toxicity', 'Alcohols',...",Congenital Abnormalities,Malformations of organs or body parts during d...,['Congenital abnormality'],Vesicle-mediated transport,ethanol,congenital abnormalities,"(DB00898, congenital abnormalities)"
3,DB01168,MESH:D000013,1,Procarbazine,Procarbazineis an antineoplastic agent indicat...,"['P21397', 'P27338']",Procarbazine is an antineoplastic in the class...,CNNCC1=CC=C(C=C1)C(=O)NC(C)C,The precise mode of cytotoxic action of procar...,[],"['Acids, Carbocyclic', 'Agents Causing Muscle ...",Congenital Abnormalities,Malformations of organs or body parts during d...,['Congenital abnormality'],Vesicle-mediated transport,procarbazine,congenital abnormalities,"(DB01168, congenital abnormalities)"
4,DB00550,MESH:D000013,1,Propylthiouracil,Propylthiouracilis a thiourea antithyroid agen...,['P07202'],Propylthiouracil is a thiourea antithyroid age...,CCCC1=CC(=O)NC(=S)N1,Propylthiouracil binds to thyroid peroxidase a...,[],"['Agents Causing Muscle Toxicity', 'Antimetabo...",Congenital Abnormalities,Malformations of organs or body parts during d...,['Congenital abnormality'],Vesicle-mediated transport,propylthiouracil,congenital abnormalities,"(DB00550, congenital abnormalities)"

In [5]:
# ============================================================
# 5. Map MiRAGE DrugBank IDs to PrimeKG drug nodes
# ============================================================

drug_nodes = node_df[node_df["node_type"] == "drug"].copy()

# PrimeKG drug node_id should correspond to DrugBank ID.
drug_nodes["node_id_norm"] = drug_nodes["node_id"].apply(canonical_drugbank_id)

drugid_to_primekg_node_index = drug_nodes.set_index("node_id_norm")["node_index"].to_dict()
drugid_to_primekg_node_name = drug_nodes.set_index("node_id_norm")["node_name"].to_dict()
drugid_to_primekg_node_source = drug_nodes.set_index("node_id_norm")["node_source"].to_dict()

mirage["primekg_drug_node_id"] = mirage["DrugID"].apply(canonical_drugbank_id)
mirage["primekg_drug_node_index"] = mirage["primekg_drug_node_id"].map(drugid_to_primekg_node_index)
mirage["primekg_drug_node_name"] = mirage["primekg_drug_node_id"].map(drugid_to_primekg_node_name)
mirage["primekg_drug_node_source"] = mirage["primekg_drug_node_id"].map(drugid_to_primekg_node_source)

mirage["drug_in_primekg"] = mirage["primekg_drug_node_index"].notna()

# ============================================================
# Drug mapping summary
# ============================================================

total_unique_drugs = mirage["DrugID"].nunique()
unmatched_drugids = (
    mirage.loc[~mirage["drug_in_primekg"], "DrugID"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .tolist()
)

matched_unique_drugs = total_unique_drugs - len(unmatched_drugids)

print("Drug mapping summary:")
print(f"Total unique MiRAGE DrugID: {total_unique_drugs:,}")
print(f"Matched unique DrugID in PrimeKG: {matched_unique_drugs:,}")
print(f"Unmatched unique DrugID: {len(unmatched_drugids):,}")
print(f"Unmatched unique DrugID ratio: {len(unmatched_drugids) / total_unique_drugs:.4%}")
print(f"Unmatched DrugIDs: {unmatched_drugids}")

row_unmatched_drugs = (~mirage["drug_in_primekg"]).sum()
print(f"\nRows with unmatched drug: {row_unmatched_drugs:,} ({row_unmatched_drugs / len(mirage):.4%})")

print("\nMapped drug examples:")
display(
    mirage[
        ["DrugID", "DrugName", "primekg_drug_node_id", "primekg_drug_node_index", "primekg_drug_node_name", "drug_in_primekg"]
    ].head()
)

if row_unmatched_drugs > 0:
    print("\nUnmatched drug row examples:")
    display(
        mirage.loc[
            ~mirage["drug_in_primekg"],
            ["DrugID", "DrugName", "DiseaseID", "DiseaseName"]
        ].drop_duplicates().head(20)
    )

Drug mapping summary:
Total unique MiRAGE DrugID: 1,410
Matched unique DrugID in PrimeKG: 1,408
Unmatched unique DrugID: 2
Unmatched unique DrugID ratio: 0.1418%
Unmatched DrugIDs: ['DB04862', 'DB08845']

Rows with unmatched drug: 2 (0.0047%)

Mapped drug examples:

,DrugID,DrugName,primekg_drug_node_id,primekg_drug_node_index,primekg_drug_node_name,drug_in_primekg
0,DB09140,Oxygen,DB09140,14013.0,Oxygen,True
1,DB00730,Thiabendazole,DB00730,15307.0,Thiabendazole,True
2,DB00898,Ethanol,DB00898,14587.0,Ethanol,True
3,DB01168,Procarbazine,DB01168,14914.0,Procarbazine,True
4,DB00550,Propylthiouracil,DB00550,14640.0,Propylthiouracil,True

Unmatched drug row examples:

        DrugID        DrugName     DiseaseID              DiseaseName
2753   DB08845  Oxogluric acid  MESH:D001169  Arthritis, Experimental
15095  DB04862     Merimepodib  MESH:D006526              Hepatitis C

In [6]:
# ============================================================
# 6. Map MiRAGE MeSH DiseaseIDs to PrimeKG disease nodes via MONDO
# ============================================================

with open(MONDO_JSON_PATH, "r", encoding="utf-8") as f:
    mondo_json = json.load(f)

mondo_nodes = mondo_json["graphs"][0]["nodes"]


def extract_mondo_num_from_url(mondo_url):
    """
    Extract numeric MONDO ID from URLs like:
        http://purl.obolibrary.org/obo/MONDO_0001234
    Returns PrimeKG-style numeric string without leading zeros, e.g. '1234'.
    """
    if not isinstance(mondo_url, str):
        return None

    if "MONDO_" not in mondo_url:
        return None

    raw = mondo_url.split("MONDO_")[-1]
    raw = re.sub(r"\D", "", raw)

    if raw == "":
        return None

    return str(int(raw))


# Build MeSH -> set(MONDO numeric IDs)
mesh_to_mondo_nums = {}

for entry in tqdm(mondo_nodes, desc="Building MeSH -> MONDO mapping"):
    mondo_num = extract_mondo_num_from_url(entry.get("id", ""))
    if mondo_num is None:
        continue

    meta = entry.get("meta", {})
    mesh_ids = []

    # 1) xrefs: usually MESH:Dxxxxxx
    for xref in meta.get("xrefs", []):
        val = xref.get("val", "")
        if isinstance(val, str) and val.startswith("MESH:"):
            mesh = canonical_mesh_id(val, with_prefix=False)
            if not pd.isna(mesh):
                mesh_ids.append(mesh)

    # 2) basicPropertyValues exactMatch URLs, e.g. identifiers.org/mesh/Dxxxxxx
    for bp in meta.get("basicPropertyValues", []):
        pred = bp.get("pred", "")
        val = bp.get("val", "")

        if (
            isinstance(pred, str)
            and pred.endswith("exactMatch")
            and isinstance(val, str)
            and "mesh" in val.lower()
        ):
            mesh = canonical_mesh_id(val, with_prefix=False)
            if not pd.isna(mesh):
                mesh_ids.append(mesh)

    for mesh in set(mesh_ids):
        mesh_to_mondo_nums.setdefault(mesh, set()).add(mondo_num)

print(f"MeSH IDs with MONDO mapping: {len(mesh_to_mondo_nums):,}")


# PrimeKG disease nodes
disease_nodes = node_df[node_df["node_type"] == "disease"].copy()
disease_nodes["node_id_norm"] = disease_nodes["node_id"].apply(normalize_primekg_node_id)

mondo_to_primekg_node_index = disease_nodes.set_index("node_id_norm")["node_index"].to_dict()
mondo_to_primekg_node_name = disease_nodes.set_index("node_id_norm")["node_name"].to_dict()
mondo_to_primekg_node_source = disease_nodes.set_index("node_id_norm")["node_source"].to_dict()


def map_mesh_to_primekg_disease(mesh_id):
    """
    Input:
        mesh_id: MiRAGE DiseaseID, e.g. 'MESH:D000013'

    Returns:
        primekg_disease_node_id, primekg_disease_node_index, primekg_disease_node_name, primekg_disease_node_source
    """
    mesh = canonical_mesh_id(mesh_id, with_prefix=False)

    if pd.isna(mesh):
        return pd.NA, pd.NA, pd.NA, pd.NA

    if mesh not in mesh_to_mondo_nums:
        return pd.NA, pd.NA, pd.NA, pd.NA

    candidate_mondos = sorted(mesh_to_mondo_nums[mesh], key=lambda x: int(x))

    # Prefer MONDO IDs that actually exist in PrimeKG disease nodes.
    for mondo_num in candidate_mondos:
        mondo_norm = normalize_primekg_node_id(mondo_num)

        if mondo_norm in mondo_to_primekg_node_index:
            return (
                mondo_norm,
                mondo_to_primekg_node_index[mondo_norm],
                mondo_to_primekg_node_name[mondo_norm],
                mondo_to_primekg_node_source[mondo_norm],
            )

    return pd.NA, pd.NA, pd.NA, pd.NA


mapped_diseases = mirage["DiseaseID"].apply(map_mesh_to_primekg_disease)

mirage["primekg_disease_node_id"] = [x[0] for x in mapped_diseases]
mirage["primekg_disease_node_index"] = [x[1] for x in mapped_diseases]
mirage["primekg_disease_node_name"] = [x[2] for x in mapped_diseases]
mirage["primekg_disease_node_source"] = [x[3] for x in mapped_diseases]

mirage["disease_in_primekg"] = mirage["primekg_disease_node_index"].notna()

# ============================================================
# Disease mapping summary
# ============================================================

total_unique_diseases = mirage["DiseaseID"].nunique()
unmatched_diseaseids = (
    mirage.loc[~mirage["disease_in_primekg"], "DiseaseID"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .tolist()
)

matched_unique_diseases = total_unique_diseases - len(unmatched_diseaseids)

print("\nDisease mapping summary:")
print(f"Total unique MiRAGE DiseaseID: {total_unique_diseases:,}")
print(f"Matched unique DiseaseID in PrimeKG: {matched_unique_diseases:,}")
print(f"Unmatched unique DiseaseID: {len(unmatched_diseaseids):,}")
print(f"Unmatched unique DiseaseID ratio: {len(unmatched_diseaseids) / total_unique_diseases:.4%}")

row_unmatched_diseases = (~mirage["disease_in_primekg"]).sum()
print(f"\nRows with unmatched disease: {row_unmatched_diseases:,} ({row_unmatched_diseases / len(mirage):.4%})")

print("\nFirst 50 unmatched DiseaseIDs:")
print(unmatched_diseaseids[:50])

print("\nMapped disease examples:")
display(
    mirage[
        [
            "DiseaseID",
            "DiseaseName",
            "primekg_disease_node_id",
            "primekg_disease_node_index",
            "primekg_disease_node_name",
            "disease_in_primekg",
        ]
    ].head()
)

if row_unmatched_diseases > 0:
    print("\nUnmatched disease row examples:")
    display(
        mirage.loc[
            ~mirage["disease_in_primekg"],
            ["DrugID", "DrugName", "DiseaseID", "DiseaseName", "DiseaseDescription"]
        ].drop_duplicates(subset=["DiseaseID"]).head(20)
    )

Building MeSH -> MONDO mapping:   0%|          | 0/57384 [00:00<?, ?it/s]

MeSH IDs with MONDO mapping: 8,208

Disease mapping summary:
Total unique MiRAGE DiseaseID: 1,573
Matched unique DiseaseID in PrimeKG: 861
Unmatched unique DiseaseID: 712
Unmatched unique DiseaseID ratio: 45.2638%

Rows with unmatched disease: 19,593 (46.4289%)

First 50 unmatched DiseaseIDs:
['MESH:D000015', 'MESH:D000022', 'MESH:D000067877', 'MESH:D000068079', 'MESH:D000070642', 'MESH:D000072660', 'MESH:D000075222', 'MESH:D000077192', 'MESH:D000077195', 'MESH:D000077216', 'MESH:D000077273', 'MESH:D000138', 'MESH:D000141', 'MESH:D000152', 'MESH:D000210', 'MESH:D000224', 'MESH:D000312', 'MESH:D000361', 'MESH:D000382', 'MESH:D000402', 'MESH:D000419', 'MESH:D000435', 'MESH:D000437', 'MESH:D000471', 'MESH:D000506', 'MESH:D000544', 'MESH:D000647', 'MESH:D000690', 'MESH:D000744', 'MESH:D000749', 'MESH:D000756', 'MESH:D000782', 'MESH:D000783', 'MESH:D000784', 'MESH:D000787', 'MESH:D000853', 'MESH:D000855', 'MESH:D000856', 'MESH:D000860', 'MESH:D001008', 'MESH:D001010', 'MESH:D001019', 'MESH:D001049', 'MESH:D001068', 'MESH:D001139', 'MESH:D001145', 'MESH:D001157', 'MESH:D001169', 'MESH:D001171', 'MESH:D001201']

Mapped disease examples:

,DiseaseID,DiseaseName,primekg_disease_node_id,primekg_disease_node_index,primekg_disease_node_name,disease_in_primekg
0,MESH:D000013,Congenital Abnormalities,839,35598,congenital abnormality,True
1,MESH:D000013,Congenital Abnormalities,839,35598,congenital abnormality,True
2,MESH:D000013,Congenital Abnormalities,839,35598,congenital abnormality,True
3,MESH:D000013,Congenital Abnormalities,839,35598,congenital abnormality,True
4,MESH:D000013,Congenital Abnormalities,839,35598,congenital abnormality,True

Unmatched disease row examples:

,DrugID,DrugName,DiseaseID,DiseaseName,DiseaseDescription
110,DB00755,Tretinoin,MESH:D000015,"Abnormalities, Multiple",Congenital abnormalities that affect more than...
137,DB00619,Imatinib,MESH:D000022,"Abortion, Spontaneous",Expulsion of the product of FERTILIZATION befo...
151,DB02709,Resveratrol,MESH:D000067877,Autism Spectrum Disorder,Wide continuum of associated cognitive and neu...
156,DB02709,Resveratrol,MESH:D000068079,Motor Disorders,Motor skills deficits that significantly and p...
165,DB11672,Curcumin,MESH:D000070642,"Brain Injuries, Traumatic",A form of acquired brain injury which occurs w...
167,DB01112,Cefuroxime,MESH:D000072660,Teratozoospermia,Conditions in which sperm show abnormal morpho...
170,DB00394,Beclomethasone dipropionate,MESH:D000075222,Essential Hypertension,"Hypertension that occurs without known cause, ..."
174,DB05294,Vandetanib,MESH:D000077192,Adenocarcinoma of Lung,A carcinoma originating in the lung and the mo...
188,DB00290,Bleomycin,MESH:D000077195,Squamous Cell Carcinoma of Head and Neck,The most common type of head and neck carcinom...
197,DB00997,Doxorubicin,MESH:D000077216,"Carcinoma, Ovarian Epithelial",A malignant neoplasm that originates in cells ...
203,DB01098,Rosuvastatin,MESH:D000077273,"Thyroid Cancer, Papillary",An ADENOCARCINOMA that originates from follicu...
212,DB00898,Ethanol,MESH:D000138,Acidosis,A pathologic condition of acid accumulation or...
298,DB00531,Cyclophosphamide,MESH:D000141,"Acidosis, Renal Tubular",A group of genetic disorders of the KIDNEY TUB...
316,DB00294,Etonogestrel,MESH:D000152,Acne Vulgaris,A chronic disorder of the pilosebaceous appara...
363,DB00399,Zoledronic acid,MESH:D000210,Acute-Phase Reaction,An early local inflammatory reaction to insult...
364,DB00687,Fludrocortisone,MESH:D000224,Addison Disease,An adrenal disease characterized by the progre...
502,DB01708,Prasterone,MESH:D000312,"Adrenal Hyperplasia, Congenital",A group of inherited disorders of the ADRENAL ...
504,DB00795,Sulfasalazine,MESH:D000361,Agammaglobulinemia,An immunologic deficiency state characterized ...
565,DB00772,Malathion,MESH:D000382,Agricultural Workers' Diseases,Diseases in persons engaged in cultivating and...
568,DB00394,Beclomethasone dipropionate,MESH:D000402,Airway Obstruction,Any hindrance to the passage of air into and o...

In [7]:
# ============================================================
# 7. Initial graph-present / graph-absent split
# ============================================================

mirage["graph_present"] = mirage["drug_in_primekg"] & mirage["disease_in_primekg"]
mirage["graph_absent"] = ~mirage["graph_present"]

# More detailed absence type
def get_absence_type(row):
    if row["drug_in_primekg"] and row["disease_in_primekg"]:
        return "graph_present"
    if (not row["drug_in_primekg"]) and row["disease_in_primekg"]:
        return "drug_absent"
    if row["drug_in_primekg"] and (not row["disease_in_primekg"]):
        return "disease_absent"
    return "drug_and_disease_absent"

mirage["graph_absence_type"] = mirage.apply(get_absence_type, axis=1)

# ============================================================
# Summary
# ============================================================

n_total = len(mirage)
n_present = int(mirage["graph_present"].sum())
n_absent = int(mirage["graph_absent"].sum())

print("Initial graph-present / graph-absent split:")
print(f"Total MiRAGE pairs: {n_total:,}")
print(f"Graph-present pairs: {n_present:,} ({n_present / n_total:.4%})")
print(f"Graph-absent pairs: {n_absent:,} ({n_absent / n_total:.4%})")

print("\nAbsence type distribution:")
absence_counts = (
    mirage["graph_absence_type"]
    .value_counts()
    .rename_axis("graph_absence_type")
    .reset_index(name="count")
)
absence_counts["ratio"] = absence_counts["count"] / n_total
display(absence_counts)

print("\nDrug/Disease PrimeKG mapping crosstab:")
display(
    pd.crosstab(
        mirage["drug_in_primekg"],
        mirage["disease_in_primekg"],
        rownames=["drug_in_primekg"],
        colnames=["disease_in_primekg"],
        margins=True,
    )
)

# Unique entity-level summary
unique_drug_summary = mirage[["DrugID", "drug_in_primekg"]].drop_duplicates()
unique_disease_summary = mirage[["DiseaseID", "disease_in_primekg"]].drop_duplicates()

print("\nUnique entity-level mapping summary:")
print(
    f"Unique drugs in PrimeKG: {unique_drug_summary['drug_in_primekg'].sum():,} / "
    f"{len(unique_drug_summary):,} "
    f"({unique_drug_summary['drug_in_primekg'].mean():.4%})"
)
print(
    f"Unique diseases in PrimeKG: {unique_disease_summary['disease_in_primekg'].sum():,} / "
    f"{len(unique_disease_summary):,} "
    f"({unique_disease_summary['disease_in_primekg'].mean():.4%})"
)

print("\nGraph-present examples:")
display(
    mirage.loc[
        mirage["graph_present"],
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "primekg_drug_node_index",
            "primekg_disease_node_index",
            "graph_absence_type",
        ],
    ].head()
)

print("\nGraph-absent examples:")
display(
    mirage.loc[
        mirage["graph_absent"],
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "drug_in_primekg",
            "disease_in_primekg",
            "graph_absence_type",
        ],
    ].head()
)

Initial graph-present / graph-absent split:
Total MiRAGE pairs: 42,200
Graph-present pairs: 22,606 (53.5687%)
Graph-absent pairs: 19,594 (46.4313%)

Absence type distribution:

        graph_absence_type  count     ratio
0            graph_present  22606  0.535687
1           disease_absent  19592  0.464265
2  drug_and_disease_absent      1  0.000024
3              drug_absent      1  0.000024

Drug/Disease PrimeKG mapping crosstab:

disease_in_primekg  False   True    All
drug_in_primekg
False                   1      1      2
True                19592  22606  42198
All                 19593  22607  42200

Unique entity-level mapping summary:
Unique drugs in PrimeKG: 1,408 / 1,410 (99.8582%)
Unique diseases in PrimeKG: 861 / 1,573 (54.7362%)

Graph-present examples:

,DrugID,DrugName,DiseaseID,DiseaseName,primekg_drug_node_index,primekg_disease_node_index,graph_absence_type
0,DB09140,Oxygen,MESH:D000013,Congenital Abnormalities,14013.0,35598,graph_present
1,DB00730,Thiabendazole,MESH:D000013,Congenital Abnormalities,15307.0,35598,graph_present
2,DB00898,Ethanol,MESH:D000013,Congenital Abnormalities,14587.0,35598,graph_present
3,DB01168,Procarbazine,MESH:D000013,Congenital Abnormalities,14914.0,35598,graph_present
4,DB00550,Propylthiouracil,MESH:D000013,Congenital Abnormalities,14640.0,35598,graph_present

Graph-absent examples:

,DrugID,DrugName,DiseaseID,DiseaseName,drug_in_primekg,disease_in_primekg,graph_absence_type
110,DB00755,Tretinoin,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent
111,DB00794,Primidone,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent
112,DB14001,alpha-Tocopherol succinate,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent
113,DB00586,Diclofenac,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent
114,DB01097,Leflunomide,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent

In [8]:
# ============================================================
# 8. Mark MiRAGE pairs already present in PrimeKG drug-disease relations
# ============================================================

def load_primekg_known_drug_disease_pairs():
    """
    Load known drug-disease pairs from PrimeKG.

    Returns
    -------
    known_pairs : set of (drug_node_id, disease_node_id)
        IDs are normalized PrimeKG node IDs.
    known_pair_relations : dict
        (drug_node_id, disease_node_id) -> set(relations)
    kg_source : str
        Which PrimeKG file was used.
    """
    known_pairs = set()
    known_pair_relations = {}

    # Prefer kg.csv if available because it usually has x_type/y_type/x_id/y_id.
    if PRIMEKG_KG_PATH.exists():
        kg_source = str(PRIMEKG_KG_PATH)
        kg = pd.read_csv(PRIMEKG_KG_PATH)

        required_cols = {"x_type", "x_id", "relation", "y_type", "y_id"}
        missing = required_cols - set(kg.columns)
        assert not missing, f"PrimeKG kg.csv missing columns: {missing}"

        kg["x_type"] = kg["x_type"].astype(str)
        kg["y_type"] = kg["y_type"].astype(str)
        kg["relation"] = kg["relation"].astype(str)
        kg["x_id"] = kg["x_id"].apply(normalize_primekg_node_id)
        kg["y_id"] = kg["y_id"].apply(normalize_primekg_node_id)

        dd = kg[kg["relation"].isin(PRIMEKG_DD_RELATIONS)].copy()

        for _, row in tqdm(dd.iterrows(), total=len(dd), desc="Collect PrimeKG known DD pairs"):
            x_type = row["x_type"]
            y_type = row["y_type"]
            rel = row["relation"]

            if x_type == "drug" and y_type == "disease":
                drug_id = normalize_primekg_node_id(row["x_id"])
                disease_id = normalize_primekg_node_id(row["y_id"])
            elif x_type == "disease" and y_type == "drug":
                drug_id = normalize_primekg_node_id(row["y_id"])
                disease_id = normalize_primekg_node_id(row["x_id"])
            else:
                continue

            if pd.isna(drug_id) or pd.isna(disease_id):
                continue

            pair = (drug_id, disease_id)
            known_pairs.add(pair)
            known_pair_relations.setdefault(pair, set()).add(rel)

        return known_pairs, known_pair_relations, kg_source

    # Fallback to edges.csv if kg.csv is unavailable.
    if PRIMEKG_EDGES_PATH.exists():
        kg_source = str(PRIMEKG_EDGES_PATH)
        edges = pd.read_csv(PRIMEKG_EDGES_PATH)

        required_cols = {"x_index", "y_index", "relation"}
        missing = required_cols - set(edges.columns)
        assert not missing, f"PrimeKG edges.csv missing columns: {missing}"

        nodes_by_index = (
            node_df
            .set_index("node_index")[["node_id", "node_type", "node_name"]]
            .to_dict("index")
        )

        edges["relation"] = edges["relation"].astype(str)
        dd = edges[edges["relation"].isin(PRIMEKG_DD_RELATIONS)].copy()

        for _, row in tqdm(dd.iterrows(), total=len(dd), desc="Collect PrimeKG known DD pairs"):
            x_idx = row["x_index"]
            y_idx = row["y_index"]
            rel = row["relation"]

            if x_idx not in nodes_by_index or y_idx not in nodes_by_index:
                continue

            x_node = nodes_by_index[x_idx]
            y_node = nodes_by_index[y_idx]

            if x_node["node_type"] == "drug" and y_node["node_type"] == "disease":
                drug_id = normalize_primekg_node_id(x_node["node_id"])
                disease_id = normalize_primekg_node_id(y_node["node_id"])
            elif x_node["node_type"] == "disease" and y_node["node_type"] == "drug":
                drug_id = normalize_primekg_node_id(y_node["node_id"])
                disease_id = normalize_primekg_node_id(x_node["node_id"])
            else:
                continue

            if pd.isna(drug_id) or pd.isna(disease_id):
                continue

            pair = (drug_id, disease_id)
            known_pairs.add(pair)
            known_pair_relations.setdefault(pair, set()).add(rel)

        return known_pairs, known_pair_relations, kg_source

    raise FileNotFoundError(
        f"Neither {PRIMEKG_KG_PATH} nor {PRIMEKG_EDGES_PATH} exists."
    )


primekg_known_dd_pairs, primekg_known_dd_pair_relations, primekg_dd_source = (
    load_primekg_known_drug_disease_pairs()
)

print(f"PrimeKG DD source: {primekg_dd_source}")
print(f"Known PrimeKG drug-disease pairs in selected relations: {len(primekg_known_dd_pairs):,}")


def mirage_pair_in_primekg_known_dd(row):
    """
    Only graph-present rows can overlap PrimeKG by node ID.
    Graph-absent rows are marked False because at least one node is absent.
    """
    if not row["graph_present"]:
        return False

    pair = (
        normalize_primekg_node_id(row["primekg_drug_node_id"]),
        normalize_primekg_node_id(row["primekg_disease_node_id"]),
    )
    return pair in primekg_known_dd_pairs


def mirage_primekg_known_dd_relations(row):
    if not row["graph_present"]:
        return ""

    pair = (
        normalize_primekg_node_id(row["primekg_drug_node_id"]),
        normalize_primekg_node_id(row["primekg_disease_node_id"]),
    )

    return "|".join(sorted(primekg_known_dd_pair_relations.get(pair, [])))


mirage["pair_in_primekg_known_dd"] = mirage.apply(mirage_pair_in_primekg_known_dd, axis=1)
mirage["primekg_known_dd_relations"] = mirage.apply(mirage_primekg_known_dd_relations, axis=1)

# ============================================================
# Summary
# ============================================================

n_primekg_overlap = int(mirage["pair_in_primekg_known_dd"].sum())
n_graph_present = int(mirage["graph_present"].sum())

print("\nMiRAGE overlap with PrimeKG known DD relations:")
print(f"Overlapping rows: {n_primekg_overlap:,} / {len(mirage):,} ({n_primekg_overlap / len(mirage):.4%})")
print(f"Overlapping among graph-present rows: {n_primekg_overlap:,} / {n_graph_present:,} ({n_primekg_overlap / n_graph_present:.4%})")

print("\nOverlap relation distribution:")
display(
    mirage.loc[mirage["pair_in_primekg_known_dd"], "primekg_known_dd_relations"]
    .value_counts()
    .rename_axis("primekg_known_dd_relations")
    .reset_index(name="count")
)

print("\nPrimeKG-overlap examples:")
display(
    mirage.loc[
        mirage["pair_in_primekg_known_dd"],
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "primekg_drug_node_id",
            "primekg_disease_node_id",
            "primekg_known_dd_relations",
        ],
    ].head(20)
)

Collect PrimeKG known DD pairs:   0%|          | 0/85262 [00:00<?, ?it/s]

PrimeKG DD source: ..\data\kg\kg.csv
Known PrimeKG drug-disease pairs in selected relations: 42,383

MiRAGE overlap with PrimeKG known DD relations:
Overlapping rows: 2,678 / 42,200 (6.3460%)
Overlapping among graph-present rows: 2,678 / 22,606 (11.8464%)

Overlap relation distribution:

       primekg_known_dd_relations  count
0                contraindication   1638
1                      indication    803
2                   off-label use    209
3     contraindication|indication     14
4        indication|off-label use     10
5  contraindication|off-label use      4

PrimeKG-overlap examples:

,DrugID,DrugName,DiseaseID,DiseaseName,primekg_drug_node_id,primekg_disease_node_id,primekg_known_dd_relations
271,DB01016,Glyburide,MESH:D000140,"Acidosis, Lactic",DB01016,6040,contraindication
273,DB00495,Zidovudine,MESH:D000140,"Acidosis, Lactic",DB00495,6040,contraindication
278,DB00625,Efavirenz,MESH:D000140,"Acidosis, Lactic",DB00625,6040,contraindication
285,DB00709,Lamivudine,MESH:D000140,"Acidosis, Lactic",DB00709,6040,contraindication
286,DB00649,Stavudine,MESH:D000140,"Acidosis, Lactic",DB00649,6040,contraindication
290,DB00900,Didanosine,MESH:D000140,"Acidosis, Lactic",DB00900,6040,contraindication
292,DB00331,Metformin,MESH:D000140,"Acidosis, Lactic",DB00331,6040,contraindication
295,DB00300,Tenofovir disoproxil,MESH:D000140,"Acidosis, Lactic",DB00300,6040,contraindication
345,DB00503,Ritonavir,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00503,12268,indication
346,DB00943,Zalcitabine,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00943,12268,indication
347,DB00224,Indinavir,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00224,12268,indication
348,DB00900,Didanosine,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00900,12268,indication
350,DB00649,Stavudine,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00649,12268,indication
352,DB00495,Zidovudine,MESH:D000163,Acquired Immunodeficiency Syndrome,DB00495,12268,indication
359,DB06791,Lanreotide,MESH:D000172,Acromegaly,DB06791,19933,indication
361,DB01200,Bromocriptine,MESH:D000172,Acromegaly,DB01200,19933,indication
468,DB00215,Citalopram,MESH:D000275,Adjustment Disorders,DB00215,5379,indication
485,DB00620,Triamcinolone,MESH:D000309,Adrenal Insufficiency,DB00620,4,indication
487,DB00292,Etomidate,MESH:D000309,Adrenal Insufficiency,DB00292,4,contraindication
489,DB00959,Methylprednisolone,MESH:D000309,Adrenal Insufficiency,DB00959,4,indication

In [9]:
# ============================================================
# 9. Mark MiRAGE pairs overlapping raw LLM training sources:
#    RepoDB and DrugRepoBank
# ============================================================

def add_train_source_pair(pair_dict, drug_id, disease_name, source_name):
    """
    Add a raw train-source pair using:
        key = (DrugBank ID, normalized disease name)
    """
    drug_id = canonical_drugbank_id(drug_id)
    disease_norm = normalize_text(disease_name)

    if pd.isna(drug_id) or disease_norm == "":
        return

    key = (drug_id, disease_norm)
    pair_dict.setdefault(key, set()).add(source_name)


train_source_name_pair_sources = {}

# ------------------------------------------------------------
# 9.1 RepoDB pairs
# ------------------------------------------------------------
# RepoDB example:
# "drug_name","drugbank_id","ind_name","ind_id","NCT","status","phase","DetailedStatus"
#
# For overlap filtering, use drugbank_id + ind_name.
# We do not filter by status here, because the LLM training material was generated
# from RepoDB drug-disease pairs, and any exact pair overlap should be removed
# from MiRAGE external test.
# ------------------------------------------------------------

repodb_pairs_before = len(train_source_name_pair_sources)

for _, row in repodb_df.iterrows():
    add_train_source_pair(
        train_source_name_pair_sources,
        drug_id=row.get("drugbank_id", pd.NA),
        disease_name=row.get("ind_name", pd.NA),
        source_name="RepoDB:ind_name",
    )

repodb_pairs_added = len(train_source_name_pair_sources) - repodb_pairs_before

print("RepoDB raw train-source pairs loaded:")
print(f"Unique name-level pairs after RepoDB: {len(train_source_name_pair_sources):,}")
print(f"New unique pairs added by RepoDB: {repodb_pairs_added:,}")


# ------------------------------------------------------------
# 9.2 DrugRepoBank pairs
# ------------------------------------------------------------
# DrugRepoBank columns include:
#   DrugID, Disease, NewDisease
#
# For drug repositioning, NewDisease is usually the target/new disease.
# However, because the training material may have used the full row context,
# we conservatively include both:
#   DrugID + NewDisease
#   DrugID + Disease
#
# Later the output keeps source tags so you can inspect how many overlaps come
# from each column.
# ------------------------------------------------------------

drb_pairs_before = len(train_source_name_pair_sources)

for _, row in drugrepobank_df.iterrows():
    drug_id = row.get("DrugID", pd.NA)

    if "NewDisease" in drugrepobank_df.columns:
        add_train_source_pair(
            train_source_name_pair_sources,
            drug_id=drug_id,
            disease_name=row.get("NewDisease", pd.NA),
            source_name="DrugRepoBank:NewDisease",
        )

    if "Disease" in drugrepobank_df.columns:
        add_train_source_pair(
            train_source_name_pair_sources,
            drug_id=drug_id,
            disease_name=row.get("Disease", pd.NA),
            source_name="DrugRepoBank:Disease",
        )

drb_pairs_added = len(train_source_name_pair_sources) - drb_pairs_before

print("\nDrugRepoBank raw train-source pairs loaded:")
print(f"Unique name-level pairs after DrugRepoBank: {len(train_source_name_pair_sources):,}")
print(f"New unique pairs added by DrugRepoBank: {drb_pairs_added:,}")


# ------------------------------------------------------------
# 9.3 Mark MiRAGE overlaps
# ------------------------------------------------------------

def get_train_source_overlap_sources(row):
    key = (
        canonical_drugbank_id(row["DrugID"]),
        normalize_text(row["DiseaseName"]),
    )

    sources = train_source_name_pair_sources.get(key, set())
    return "|".join(sorted(sources))


mirage["train_source_overlap_sources"] = mirage.apply(
    get_train_source_overlap_sources,
    axis=1,
)

mirage["pair_in_llm_train_source_raw"] = mirage["train_source_overlap_sources"].astype(str).str.len() > 0


# ============================================================
# Summary
# ============================================================

n_train_overlap = int(mirage["pair_in_llm_train_source_raw"].sum())

print("\nMiRAGE overlap with raw LLM training sources:")
print(
    f"Overlapping rows: {n_train_overlap:,} / {len(mirage):,} "
    f"({n_train_overlap / len(mirage):.4%})"
)

print("\nOverlap source distribution:")
display(
    mirage.loc[mirage["pair_in_llm_train_source_raw"], "train_source_overlap_sources"]
    .value_counts()
    .rename_axis("train_source_overlap_sources")
    .reset_index(name="count")
)

print("\nOverlap by graph-present / graph-absent:")
display(
    pd.crosstab(
        mirage["graph_absence_type"],
        mirage["pair_in_llm_train_source_raw"],
        rownames=["graph_absence_type"],
        colnames=["pair_in_llm_train_source_raw"],
        margins=True,
    )
)

print("\nRaw train-source overlap examples:")
display(
    mirage.loc[
        mirage["pair_in_llm_train_source_raw"],
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "graph_absence_type",
            "train_source_overlap_sources",
        ],
    ].head(30)
)

RepoDB raw train-source pairs loaded:
Unique name-level pairs after RepoDB: 10,602
New unique pairs added by RepoDB: 10,602

DrugRepoBank raw train-source pairs loaded:
Unique name-level pairs after DrugRepoBank: 10,895
New unique pairs added by DrugRepoBank: 293

MiRAGE overlap with raw LLM training sources:
Overlapping rows: 958 / 42,200 (2.2701%)

Overlap source distribution:

           train_source_overlap_sources  count
0                       RepoDB:ind_name    945
1  DrugRepoBank:Disease|RepoDB:ind_name      7
2                  DrugRepoBank:Disease      6

Overlap by graph-present / graph-absent:

pair_in_llm_train_source_raw  False  True    All
graph_absence_type
disease_absent                19194   398  19592
drug_absent                       1     0      1
drug_and_disease_absent           1     0      1
graph_present                 22046   560  22606
All                           41242   958  42200

Raw train-source overlap examples:

,DrugID,DrugName,DiseaseID,DiseaseName,graph_absence_type,train_source_overlap_sources
318,DB00977,Ethinylestradiol,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
322,DB00210,Adapalene,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
324,DB00755,Tretinoin,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
328,DB01190,Clindamycin,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
329,DB00548,Azelaic acid,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
331,DB00250,Dapsone,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
333,DB00759,Tetracycline,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
337,DB00199,Erythromycin,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
339,DB09096,Benzoyl peroxide,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
340,DB00717,Norethisterone,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
341,DB00957,Norgestimate,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
342,DB01017,Minocycline,MESH:D000152,Acne Vulgaris,disease_absent,RepoDB:ind_name
359,DB06791,Lanreotide,MESH:D000172,Acromegaly,graph_present,RepoDB:ind_name
361,DB01200,Bromocriptine,MESH:D000172,Acromegaly,graph_present,RepoDB:ind_name
364,DB00687,Fludrocortisone,MESH:D000224,Addison Disease,disease_absent,RepoDB:ind_name
365,DB00741,Hydrocortisone,MESH:D000224,Addison Disease,disease_absent,RepoDB:ind_name
657,DB00475,Chlordiazepoxide,MESH:D000430,Alcohol Withdrawal Delirium,graph_present,RepoDB:ind_name
659,DB00829,Diazepam,MESH:D000430,Alcohol Withdrawal Delirium,graph_present,RepoDB:ind_name
747,DB00350,Minoxidil,MESH:D000505,Alopecia,graph_present,RepoDB:ind_name
974,DB00740,Riluzole,MESH:D000690,Amyotrophic Lateral Sclerosis,disease_absent,DrugRepoBank:Disease|RepoDB:ind_name
995,DB00668,Epinephrine,MESH:D000707,Anaphylaxis,graph_present,RepoDB:ind_name
1500,DB01005,Hydroxyurea,MESH:D000755,"Anemia, Sickle Cell",graph_present,RepoDB:ind_name
1560,DB00335,Atenolol,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1572,DB01115,Nifedipine,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1578,DB00343,Diltiazem,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1586,DB01388,Mibefradil,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1590,DB01580,Oxprenolol,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1595,DB09282,Molsidomine,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1602,DB00243,Ranolazine,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name
1603,DB00381,Amlodipine,MESH:D000787,Angina Pectoris,disease_absent,RepoDB:ind_name

In [10]:
# ============================================================
# 10. Create final unseen external subsets
# ============================================================

mirage["exclude_primekg_overlap"] = mirage["pair_in_primekg_known_dd"]
mirage["exclude_llm_train_source_overlap"] = mirage["pair_in_llm_train_source_raw"]

# Final exclusion flag:
# remove any MiRAGE pair already present in shared PrimeKG DD relations
# or in raw LLM training sources.
mirage["exclude_any_overlap"] = (
    mirage["exclude_primekg_overlap"]
    | mirage["exclude_llm_train_source_overlap"]
)

# Final unseen external benchmark
mirage_unseen = mirage.loc[~mirage["exclude_any_overlap"]].copy().reset_index(drop=True)

# Split unseen benchmark into graph-present and graph-absent subsets
mirage_graph_present_unseen = (
    mirage_unseen.loc[mirage_unseen["graph_present"]]
    .copy()
    .reset_index(drop=True)
)

mirage_graph_absent_unseen = (
    mirage_unseen.loc[mirage_unseen["graph_absent"]]
    .copy()
    .reset_index(drop=True)
)

# Excluded subsets for audit
mirage_excluded_primekg_overlap = (
    mirage.loc[mirage["exclude_primekg_overlap"]]
    .copy()
    .reset_index(drop=True)
)

mirage_excluded_llm_train_source_overlap = (
    mirage.loc[mirage["exclude_llm_train_source_overlap"]]
    .copy()
    .reset_index(drop=True)
)

mirage_excluded_any_overlap = (
    mirage.loc[mirage["exclude_any_overlap"]]
    .copy()
    .reset_index(drop=True)
)

# ============================================================
# Summary
# ============================================================

n_total = len(mirage)
n_primekg = int(mirage["exclude_primekg_overlap"].sum())
n_llm_train = int(mirage["exclude_llm_train_source_overlap"].sum())
n_any = int(mirage["exclude_any_overlap"].sum())

print("Final MiRAGE external split summary:")
print(f"Original MiRAGE pairs: {n_total:,}")
print(f"Excluded due to PrimeKG known DD overlap: {n_primekg:,} ({n_primekg / n_total:.4%})")
print(f"Excluded due to raw LLM train-source overlap: {n_llm_train:,} ({n_llm_train / n_total:.4%})")
print(f"Excluded due to any overlap union: {n_any:,} ({n_any / n_total:.4%})")
print(f"Remaining unseen MiRAGE pairs: {len(mirage_unseen):,} ({len(mirage_unseen) / n_total:.4%})")

print("\nFinal unseen subsets:")
print(
    f"Graph-present unseen: {len(mirage_graph_present_unseen):,} "
    f"({len(mirage_graph_present_unseen) / n_total:.4%} of original; "
    f"{len(mirage_graph_present_unseen) / len(mirage_unseen):.4%} of unseen)"
)
print(
    f"Graph-absent unseen: {len(mirage_graph_absent_unseen):,} "
    f"({len(mirage_graph_absent_unseen) / n_total:.4%} of original; "
    f"{len(mirage_graph_absent_unseen) / len(mirage_unseen):.4%} of unseen)"
)

print("\nOverlap reason crosstab:")
display(
    pd.crosstab(
        mirage["exclude_primekg_overlap"],
        mirage["exclude_llm_train_source_overlap"],
        rownames=["exclude_primekg_overlap"],
        colnames=["exclude_llm_train_source_overlap"],
        margins=True,
    )
)

print("\nFinal subset by graph absence type:")
final_subset_summary = (
    mirage_unseen["graph_absence_type"]
    .value_counts()
    .rename_axis("graph_absence_type")
    .reset_index(name="count")
)
final_subset_summary["ratio_of_unseen"] = final_subset_summary["count"] / len(mirage_unseen)
final_subset_summary["ratio_of_original"] = final_subset_summary["count"] / n_total
display(final_subset_summary)

print("\nExcluded rows by graph absence type:")
excluded_subset_summary = (
    mirage_excluded_any_overlap["graph_absence_type"]
    .value_counts()
    .rename_axis("graph_absence_type")
    .reset_index(name="count")
)
excluded_subset_summary["ratio_of_excluded"] = excluded_subset_summary["count"] / len(mirage_excluded_any_overlap)
excluded_subset_summary["ratio_of_original"] = excluded_subset_summary["count"] / n_total
display(excluded_subset_summary)

print("\nFinal graph-present unseen examples:")
display(
    mirage_graph_present_unseen[
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "primekg_drug_node_id",
            "primekg_disease_node_id",
            "graph_absence_type",
            "exclude_primekg_overlap",
            "exclude_llm_train_source_overlap",
        ]
    ].head(10)
)

print("\nFinal graph-absent unseen examples:")
display(
    mirage_graph_absent_unseen[
        [
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "drug_in_primekg",
            "disease_in_primekg",
            "graph_absence_type",
            "exclude_primekg_overlap",
            "exclude_llm_train_source_overlap",
        ]
    ].head(10)
)

# ============================================================
# Sanity checks
# ============================================================

assert len(mirage_unseen) + len(mirage_excluded_any_overlap) == len(mirage)
assert not mirage_unseen["exclude_any_overlap"].any()
assert not mirage_graph_present_unseen["exclude_any_overlap"].any()
assert not mirage_graph_absent_unseen["exclude_any_overlap"].any()
assert mirage_graph_present_unseen["graph_present"].all()
assert mirage_graph_absent_unseen["graph_absent"].all()

print("\nSanity checks passed.")

Final MiRAGE external split summary:
Original MiRAGE pairs: 42,200
Excluded due to PrimeKG known DD overlap: 2,678 (6.3460%)
Excluded due to raw LLM train-source overlap: 958 (2.2701%)
Excluded due to any overlap union: 3,214 (7.6161%)
Remaining unseen MiRAGE pairs: 38,986 (92.3839%)

Final unseen subsets:
Graph-present unseen: 19,790 (46.8957% of original; 50.7618% of unseen)
Graph-absent unseen: 19,196 (45.4882% of original; 49.2382% of unseen)

Overlap reason crosstab:

exclude_llm_train_source_overlap  False  True    All
exclude_primekg_overlap
False                             38986   536  39522
True                               2256   422   2678
All                               41242   958  42200

Final subset by graph absence type:

        graph_absence_type  count  ratio_of_unseen  ratio_of_original
0            graph_present  19790         0.507618           0.468957
1           disease_absent  19194         0.492331           0.454834
2  drug_and_disease_absent      1         0.000026           0.000024
3              drug_absent      1         0.000026           0.000024

Excluded rows by graph absence type:

  graph_absence_type  count  ratio_of_excluded  ratio_of_original
0      graph_present   2816           0.876167           0.066730
1     disease_absent    398           0.123833           0.009431

Final graph-present unseen examples:

,DrugID,DrugName,DiseaseID,DiseaseName,primekg_drug_node_id,primekg_disease_node_id,graph_absence_type,exclude_primekg_overlap,exclude_llm_train_source_overlap
0,DB09140,Oxygen,MESH:D000013,Congenital Abnormalities,DB09140,839,graph_present,False,False
1,DB00730,Thiabendazole,MESH:D000013,Congenital Abnormalities,DB00730,839,graph_present,False,False
2,DB00898,Ethanol,MESH:D000013,Congenital Abnormalities,DB00898,839,graph_present,False,False
3,DB01168,Procarbazine,MESH:D000013,Congenital Abnormalities,DB01168,839,graph_present,False,False
4,DB00550,Propylthiouracil,MESH:D000013,Congenital Abnormalities,DB00550,839,graph_present,False,False
5,DB00668,Epinephrine,MESH:D000013,Congenital Abnormalities,DB00668,839,graph_present,False,False
6,DB00307,Bexarotene,MESH:D000013,Congenital Abnormalities,DB00307,839,graph_present,False,False
7,DB00313,Valproic acid,MESH:D000013,Congenital Abnormalities,DB00313,839,graph_present,False,False
8,DB01181,Ifosfamide,MESH:D000013,Congenital Abnormalities,DB01181,839,graph_present,False,False
9,DB00347,Trimethadione,MESH:D000013,Congenital Abnormalities,DB00347,839,graph_present,False,False

Final graph-absent unseen examples:

,DrugID,DrugName,DiseaseID,DiseaseName,drug_in_primekg,disease_in_primekg,graph_absence_type,exclude_primekg_overlap,exclude_llm_train_source_overlap
0,DB00755,Tretinoin,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
1,DB00794,Primidone,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
2,DB14001,alpha-Tocopherol succinate,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
3,DB00586,Diclofenac,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
4,DB01097,Leflunomide,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
5,DB11155,Triclocarban,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
6,DB00929,Misoprostol,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
7,DB00531,Cyclophosphamide,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
8,DB00347,Trimethadione,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False
9,DB00480,Lenalidomide,MESH:D000015,"Abnormalities, Multiple",True,False,disease_absent,False,False

Sanity checks passed.

In [11]:
# ============================================================
# 11. Save MiRAGE external split summary only
# ============================================================

# Final summary output
summary_json_path = OUTPUT_DIR / "summary.json"

# Build summary dictionary
summary = {
    "dataset": "MiRAGE external split",
    "description": (
        "Final MiRAGE external benchmark after removing pairs overlapping with "
        "PrimeKG known drug-disease relations and raw LLM training sources "
        "RepoDB / DrugRepoBank."
    ),

    "original_mirage_pairs": int(len(mirage)),

    "initial_graph_present_pairs": int(mirage["graph_present"].sum()),
    "initial_graph_absent_pairs": int(mirage["graph_absent"].sum()),
    "initial_graph_present_ratio": float(mirage["graph_present"].mean()),
    "initial_graph_absent_ratio": float(mirage["graph_absent"].mean()),

    "unique_drugs_total": int(mirage[["DrugID"]].drop_duplicates().shape[0]),
    "unique_drugs_in_primekg": int(
        mirage[["DrugID", "drug_in_primekg"]]
        .drop_duplicates()["drug_in_primekg"]
        .sum()
    ),
    "unique_diseases_total": int(mirage[["DiseaseID"]].drop_duplicates().shape[0]),
    "unique_diseases_in_primekg": int(
        mirage[["DiseaseID", "disease_in_primekg"]]
        .drop_duplicates()["disease_in_primekg"]
        .sum()
    ),

    "excluded_primekg_overlap_pairs": int(mirage["exclude_primekg_overlap"].sum()),
    "excluded_llm_train_source_overlap_pairs": int(
        mirage["exclude_llm_train_source_overlap"].sum()
    ),
    "excluded_any_overlap_pairs": int(mirage["exclude_any_overlap"].sum()),

    "remaining_unseen_pairs": int(len(mirage_unseen)),
    "graph_present_unseen_pairs": int(len(mirage_graph_present_unseen)),
    "graph_absent_unseen_pairs": int(len(mirage_graph_absent_unseen)),

    "remaining_unseen_ratio_of_original": float(len(mirage_unseen) / len(mirage)),
    "graph_present_unseen_ratio_of_original": float(len(mirage_graph_present_unseen) / len(mirage)),
    "graph_absent_unseen_ratio_of_original": float(len(mirage_graph_absent_unseen) / len(mirage)),
    "graph_present_unseen_ratio_of_unseen": float(len(mirage_graph_present_unseen) / len(mirage_unseen)),
    "graph_absent_unseen_ratio_of_unseen": float(len(mirage_graph_absent_unseen) / len(mirage_unseen)),

    "primekg_dd_relations_used_for_overlap": sorted(list(PRIMEKG_DD_RELATIONS)),
    "default_external_relation_for_positive_edges": DEFAULT_EXTERNAL_RELATION,

    "use_raw_train_source_overlap_filter": bool(USE_RAW_TRAIN_SOURCE_OVERLAP_FILTER),
    "llm_train_source_overlap_filter": (
        "DrugBank ID exact match plus normalized disease-name exact match against "
        "raw RepoDB ind_name and DrugRepoBank Disease / NewDisease."
    ),
    "repodb_raw_path": str(REPODB_RAW_PATH),
    "drugrepobank_raw_path": str(DRUGREPOBANK_RAW_PATH),
    "drugrepobank_encoding": "cp1252",

    "label_note": (
        "MiRAGE is positive-only. No negative edges were sampled in this preprocessing notebook."
    ),
}

with open(summary_json_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)

print("Saved MiRAGE external split summary:")
print(f"- Summary JSON: {summary_json_path}")

print("\nSummary:")
print(json.dumps(summary, ensure_ascii=False, indent=2))

Saved MiRAGE external split summary:
- Summary JSON: ..\data\processed\summary.json

Summary:
{
  "dataset": "MiRAGE external split",
  "description": "Final MiRAGE external benchmark after removing pairs overlapping with PrimeKG known drug-disease relations and raw LLM training sources RepoDB / DrugRepoBank.",
  "original_mirage_pairs": 42200,
  "initial_graph_present_pairs": 22606,
  "initial_graph_absent_pairs": 19594,
  "initial_graph_present_ratio": 0.5356872037914692,
  "initial_graph_absent_ratio": 0.46431279620853083,
  "unique_drugs_total": 1410,
  "unique_drugs_in_primekg": 1408,
  "unique_diseases_total": 1573,
  "unique_diseases_in_primekg": 861,
  "excluded_primekg_overlap_pairs": 2678,
  "excluded_llm_train_source_overlap_pairs": 958,
  "excluded_any_overlap_pairs": 3214,
  "remaining_unseen_pairs": 38986,
  "graph_present_unseen_pairs": 19790,
  "graph_absent_unseen_pairs": 19196,
  "remaining_unseen_ratio_of_original": 0.9238388625592417,
  "graph_present_unseen_ratio_of_original": 0.46895734597156397,
  "graph_absent_unseen_ratio_of_original": 0.4548815165876777,
  "graph_present_unseen_ratio_of_unseen": 0.5076181193248859,
  "graph_absent_unseen_ratio_of_unseen": 0.4923818806751141,
  "primekg_dd_relations_used_for_overlap": [
    "contraindication",
    "indication",
    "off-label use",
    "rev_contraindication",
    "rev_indication",
    "rev_off-label use"
  ],
  "default_external_relation_for_positive_edges": "indication",
  "use_raw_train_source_overlap_filter": true,
  "llm_train_source_overlap_filter": "DrugBank ID exact match plus normalized disease-name exact match against raw RepoDB ind_name and DrugRepoBank Disease / NewDisease.",
  "repodb_raw_path": "..\\data\\repodb\\repodb.csv",
  "drugrepobank_raw_path": "..\\data\\drugrepobank\\drugrepobank.csv",
  "drugrepobank_encoding": "cp1252",
  "label_note": "MiRAGE is positive-only. No negative edges were sampled in this preprocessing notebook."
}

In [12]:
# ============================================================
# 12. Build TxGNN local node-index maps from kg_directed.csv
# ============================================================

assert PRIMEKG_KG_DIRECTED_PATH.exists(), (
    f"kg_directed.csv not found: {PRIMEKG_KG_DIRECTED_PATH}\n"
    "Please generate it using the TxGNN/PrimeKG preprocessing pipeline first."
)

kg_directed, kg_directed_enc = safe_read_csv(PRIMEKG_KG_DIRECTED_PATH)

print(f"Loaded kg_directed.csv: encoding={kg_directed_enc}, shape={kg_directed.shape}")
print("kg_directed columns:")
print(kg_directed.columns.tolist())

required_kg_directed_cols = {"x_type", "x_id", "x_idx", "relation", "y_type", "y_id", "y_idx"}
missing_kg_directed_cols = required_kg_directed_cols - set(kg_directed.columns)
assert not missing_kg_directed_cols, (
    f"kg_directed.csv missing columns: {missing_kg_directed_cols}"
)

# Normalize IDs
kg_directed["x_type"] = kg_directed["x_type"].astype(str)
kg_directed["y_type"] = kg_directed["y_type"].astype(str)
kg_directed["relation"] = kg_directed["relation"].astype(str)
kg_directed["x_id"] = kg_directed["x_id"].apply(normalize_primekg_node_id)
kg_directed["y_id"] = kg_directed["y_id"].apply(normalize_primekg_node_id)

# ============================================================
# Build type-specific local index maps
# ============================================================

def collect_local_idx_map(df, node_type):
    """
    Collect node_id -> local_idx for one node type from both x-side and y-side.

    In a DGL heterograph, local node indices are type-specific.
    """
    pieces = []

    x_part = (
        df.loc[df["x_type"] == node_type, ["x_id", "x_idx"]]
        .rename(columns={"x_id": "node_id", "x_idx": "local_idx"})
    )
    pieces.append(x_part)

    y_part = (
        df.loc[df["y_type"] == node_type, ["y_id", "y_idx"]]
        .rename(columns={"y_id": "node_id", "y_idx": "local_idx"})
    )
    pieces.append(y_part)

    out = pd.concat(pieces, ignore_index=True)
    out = out.dropna(subset=["node_id", "local_idx"]).copy()

    out["node_id"] = out["node_id"].apply(normalize_primekg_node_id)
    out["local_idx"] = out["local_idx"].astype(int)

    # Check whether a node_id maps to multiple local indices.
    conflict = (
        out.drop_duplicates()
        .groupby("node_id")["local_idx"]
        .nunique()
        .reset_index(name="n_local_idx")
    )
    conflict = conflict[conflict["n_local_idx"] > 1]

    if len(conflict) > 0:
        print(f"[WARN] {node_type}: found node_id with multiple local_idx.")
        display(conflict.head(20))

    # Keep first after dropping exact duplicates
    out = out.drop_duplicates(subset=["node_id", "local_idx"])
    out = out.drop_duplicates(subset=["node_id"], keep="first")

    return dict(zip(out["node_id"], out["local_idx"])), out


txgnn_drug_id_to_local_idx, txgnn_drug_local_df = collect_local_idx_map(kg_directed, "drug")
txgnn_disease_id_to_local_idx, txgnn_disease_local_df = collect_local_idx_map(kg_directed, "disease")

print("\nTxGNN local index map sizes:")
print(f"Drug local map size: {len(txgnn_drug_id_to_local_idx):,}")
print(f"Disease local map size: {len(txgnn_disease_id_to_local_idx):,}")

print("\nDrug local index examples:")
display(txgnn_drug_local_df.head())

print("\nDisease local index examples:")
display(txgnn_disease_local_df.head())

# ============================================================
# Check graph-present unseen coverage in kg_directed local maps
# ============================================================

tmp_gp = mirage_graph_present_unseen.copy()

tmp_gp["txgnn_drug_idx"] = tmp_gp["primekg_drug_node_id"].apply(
    lambda x: txgnn_drug_id_to_local_idx.get(normalize_primekg_node_id(x), pd.NA)
)
tmp_gp["txgnn_disease_idx"] = tmp_gp["primekg_disease_node_id"].apply(
    lambda x: txgnn_disease_id_to_local_idx.get(normalize_primekg_node_id(x), pd.NA)
)

missing_txgnn_drug_idx = tmp_gp["txgnn_drug_idx"].isna().sum()
missing_txgnn_disease_idx = tmp_gp["txgnn_disease_idx"].isna().sum()
missing_any_txgnn_idx = (
    tmp_gp["txgnn_drug_idx"].isna() | tmp_gp["txgnn_disease_idx"].isna()
).sum()

print("\nCoverage of graph-present unseen pairs in TxGNN local maps:")
print(f"Graph-present unseen rows: {len(tmp_gp):,}")
print(f"Missing TxGNN drug local idx rows: {missing_txgnn_drug_idx:,}")
print(f"Missing TxGNN disease local idx rows: {missing_txgnn_disease_idx:,}")
print(f"Missing either local idx rows: {missing_any_txgnn_idx:,}")

if missing_any_txgnn_idx > 0:
    print("\nExamples with missing TxGNN local idx:")
    display(
        tmp_gp.loc[
            tmp_gp["txgnn_drug_idx"].isna() | tmp_gp["txgnn_disease_idx"].isna(),
            [
                "DrugID",
                "DrugName",
                "DiseaseID",
                "DiseaseName",
                "primekg_drug_node_id",
                "primekg_disease_node_id",
                "txgnn_drug_idx",
                "txgnn_disease_idx",
            ],
        ].head(20)
    )
else:
    print("All graph-present unseen pairs have TxGNN local indices.")

Loaded kg_directed.csv: encoding=utf-8, shape=(4050249, 7)
kg_directed columns:
['x_type', 'x_id', 'relation', 'y_type', 'y_id', 'x_idx', 'y_idx']

TxGNN local index map sizes:
Drug local map size: 7,957
Disease local map size: 17,080

Drug local index examples:

   node_id  local_idx
0  DB09130       5810
2  DB09140       5819
3  DB00180        168
4  DB00240        228
5  DB00253        241

Disease local index examples:

                                             node_id  local_idx
0  13924_12592_14672_13460_12591_12536_30861_8146...       2502
2  11160_13119_13978_12060_12327_12670_13210_1106...       1038
5                                   8099_12497_12498      15420
6  14854_14293_14470_12380_11832_14603_14853_1176...       2962
7  33202_32776_30905_33670_33200_32740_32732_3320...      10457

Coverage of graph-present unseen pairs in TxGNN local maps:
Graph-present unseen rows: 19,790
Missing TxGNN drug local idx rows: 0
Missing TxGNN disease local idx rows: 0
Missing either local idx rows: 0
All graph-present unseen pairs have TxGNN local indices.

In [13]:
# ============================================================
# 13. Create TxGNN/GNN external positive edge table
# ============================================================

txgnn_graph_present = mirage_graph_present_unseen.copy()

# Map PrimeKG node IDs to TxGNN type-specific local indices
txgnn_graph_present["txgnn_drug_idx"] = txgnn_graph_present["primekg_drug_node_id"].apply(
    lambda x: txgnn_drug_id_to_local_idx.get(normalize_primekg_node_id(x), pd.NA)
)
txgnn_graph_present["txgnn_disease_idx"] = txgnn_graph_present["primekg_disease_node_id"].apply(
    lambda x: txgnn_disease_id_to_local_idx.get(normalize_primekg_node_id(x), pd.NA)
)

# Keep only rows evaluable by TxGNN local graph
txgnn_graph_present_evaluable = (
    txgnn_graph_present
    .dropna(subset=["txgnn_drug_idx", "txgnn_disease_idx"])
    .copy()
    .reset_index(drop=True)
)

txgnn_graph_present_evaluable["txgnn_drug_idx"] = txgnn_graph_present_evaluable["txgnn_drug_idx"].astype(int)
txgnn_graph_present_evaluable["txgnn_disease_idx"] = txgnn_graph_present_evaluable["txgnn_disease_idx"].astype(int)

# Construct row-level positive edge table first.
# This preserves every original MiRAGE row before TxGNN-edge deduplication.
txgnn_external_test_positive_edges_raw = pd.DataFrame({
    "x_type": "drug",
    "x_id": txgnn_graph_present_evaluable["primekg_drug_node_id"].apply(normalize_primekg_node_id),
    "x_idx": txgnn_graph_present_evaluable["txgnn_drug_idx"].astype(int),
    "x_name": txgnn_graph_present_evaluable["DrugName"].fillna(
        txgnn_graph_present_evaluable["primekg_drug_node_name"]
    ),

    "relation": DEFAULT_EXTERNAL_RELATION,

    "y_type": "disease",
    "y_id": txgnn_graph_present_evaluable["primekg_disease_node_id"].apply(normalize_primekg_node_id),
    "y_idx": txgnn_graph_present_evaluable["txgnn_disease_idx"].astype(int),
    "y_name": txgnn_graph_present_evaluable["DiseaseName"].fillna(
        txgnn_graph_present_evaluable["primekg_disease_node_name"]
    ),

    "label": 1,
    "source": "MiRAGE",

    # Keep original identifiers for traceability
    "original_DrugID": txgnn_graph_present_evaluable["DrugID"],
    "original_DiseaseID": txgnn_graph_present_evaluable["DiseaseID"],
    "original_DrugName": txgnn_graph_present_evaluable["DrugName"],
    "original_DiseaseName": txgnn_graph_present_evaluable["DiseaseName"],
})

txgnn_external_test_positive_edges_raw = txgnn_external_test_positive_edges_raw[
    [
        "x_type",
        "x_id",
        "x_idx",
        "x_name",
        "relation",
        "y_type",
        "y_id",
        "y_idx",
        "y_name",
        "label",
        "source",
        "original_DrugID",
        "original_DiseaseID",
        "original_DrugName",
        "original_DiseaseName",
    ]
]

# ============================================================
# Inspect duplicate TxGNN edges
# ============================================================

edge_key_cols = ["x_type", "x_idx", "relation", "y_type", "y_idx"]

dup_mask = txgnn_external_test_positive_edges_raw.duplicated(
    subset=edge_key_cols,
    keep=False,
)

n_dup_rows = int(dup_mask.sum())
n_dup_extra = int(txgnn_external_test_positive_edges_raw.duplicated(
    subset=edge_key_cols,
    keep="first",
).sum())

print("TxGNN external positive edge table summary before dedup:")
print(f"Graph-present unseen rows: {len(mirage_graph_present_unseen):,}")
print(f"TxGNN evaluable raw rows: {len(txgnn_external_test_positive_edges_raw):,}")
print(f"Rows involved in duplicated TxGNN edges: {n_dup_rows:,}")
print(f"Duplicate extra rows to remove: {n_dup_extra:,}")

if n_dup_rows > 0:
    print("\nExample duplicated TxGNN edges:")
    duplicated_examples = (
        txgnn_external_test_positive_edges_raw.loc[dup_mask]
        .sort_values(edge_key_cols)
        .head(30)
    )
    display(duplicated_examples)

    print("\nDuplicate groups summary example:")
    dup_group_summary = (
        txgnn_external_test_positive_edges_raw.loc[dup_mask]
        .groupby(edge_key_cols)
        .agg(
            n_rows=("source", "size"),
            x_id=("x_id", "first"),
            y_id=("y_id", "first"),
            x_name=("x_name", "first"),
            y_name=("y_name", "first"),
            original_DiseaseIDs=("original_DiseaseID", lambda s: "|".join(sorted(set(map(str, s))))),
            original_DiseaseNames=("original_DiseaseName", lambda s: "|".join(sorted(set(map(str, s))))),
        )
        .reset_index()
        .sort_values("n_rows", ascending=False)
        .head(20)
    )
    display(dup_group_summary)

# ============================================================
# Deduplicate for GNN positive edge evaluation
# ============================================================
# For GNN edge scoring, duplicated (drug local idx, disease local idx, relation)
# edges are identical test edges. Keep one representative row.
txgnn_external_test_positive_edges = (
    txgnn_external_test_positive_edges_raw
    .drop_duplicates(subset=edge_key_cols, keep="first")
    .copy()
    .reset_index(drop=True)
)

# Also create an audit table containing all raw rows that collapsed to the same TxGNN edge.
txgnn_external_test_duplicate_edges = (
    txgnn_external_test_positive_edges_raw.loc[dup_mask]
    .copy()
    .reset_index(drop=True)
)

# ============================================================
# Final summary and sanity checks
# ============================================================

print("\nTxGNN external positive edge table summary after dedup:")
print(f"Raw positive rows: {len(txgnn_external_test_positive_edges_raw):,}")
print(f"Deduplicated positive edges: {len(txgnn_external_test_positive_edges):,}")
print(f"Removed duplicate rows: {len(txgnn_external_test_positive_edges_raw) - len(txgnn_external_test_positive_edges):,}")

print("\nRelation distribution:")
print(txgnn_external_test_positive_edges["relation"].value_counts())

print("\nUnique counts after dedup:")
print("Unique drugs:", txgnn_external_test_positive_edges["x_id"].nunique())
print("Unique diseases:", txgnn_external_test_positive_edges["y_id"].nunique())
print(
    "Unique drug-disease edges:",
    txgnn_external_test_positive_edges[["x_id", "y_id"]].drop_duplicates().shape[0],
)

print("\nDeduplicated edge table head:")
display(txgnn_external_test_positive_edges.head())

# Sanity checks
assert (txgnn_external_test_positive_edges["x_type"] == "drug").all()
assert (txgnn_external_test_positive_edges["y_type"] == "disease").all()
assert (txgnn_external_test_positive_edges["relation"] == DEFAULT_EXTERNAL_RELATION).all()
assert (txgnn_external_test_positive_edges["label"] == 1).all()
assert txgnn_external_test_positive_edges["x_idx"].notna().all()
assert txgnn_external_test_positive_edges["y_idx"].notna().all()

dup_edges_after = txgnn_external_test_positive_edges.duplicated(
    subset=edge_key_cols
).sum()
print(f"\nDuplicated TxGNN positive edges after dedup: {dup_edges_after:,}")
assert dup_edges_after == 0

print("\nSanity checks passed.")

TxGNN external positive edge table summary before dedup:
Graph-present unseen rows: 19,790
TxGNN evaluable raw rows: 19,790
Rows involved in duplicated TxGNN edges: 74
Duplicate extra rows to remove: 37

Example duplicated TxGNN edges:

,x_type,x_id,x_idx,x_name,relation,y_type,y_id,y_idx,y_name,label,source,original_DrugID,original_DiseaseID,original_DrugName,original_DiseaseName
8213,drug,DB00006,5,Bivalirudin,indication,disease,5053,12683,Ischemia,1,MiRAGE,DB00006,MESH:D007511,Bivalirudin,Ischemia
18813,drug,DB00006,5,Bivalirudin,indication,disease,5053,12683,Acute Coronary Syndrome,1,MiRAGE,DB00006,MESH:D054058,Bivalirudin,Acute Coronary Syndrome
3694,drug,DB00264,252,Metoprolol,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00264,MESH:D003324,Metoprolol,Coronary Artery Disease
17170,drug,DB00264,252,Metoprolol,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00264,MESH:D017202,Metoprolol,Myocardial Ischemia
3697,drug,DB00335,322,Atenolol,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00335,MESH:D003324,Atenolol,Coronary Artery Disease
17165,drug,DB00335,322,Atenolol,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00335,MESH:D017202,Atenolol,Myocardial Ischemia
3684,drug,DB00343,330,Diltiazem,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00343,MESH:D003324,Diltiazem,Coronary Artery Disease
17089,drug,DB00343,330,Diltiazem,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00343,MESH:D017202,Diltiazem,Myocardial Ischemia
3710,drug,DB00353,340,Methylergometrine,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00353,MESH:D003324,Methylergometrine,Coronary Artery Disease
17122,drug,DB00353,340,Methylergometrine,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00353,MESH:D017202,Methylergometrine,Myocardial Ischemia
3723,drug,DB00381,368,Amlodipine,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00381,MESH:D003324,Amlodipine,Coronary Artery Disease
17094,drug,DB00381,368,Amlodipine,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00381,MESH:D017202,Amlodipine,Myocardial Ischemia
3715,drug,DB00435,421,Nitric Oxide,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00435,MESH:D003324,Nitric Oxide,Coronary Artery Disease
17111,drug,DB00435,421,Nitric Oxide,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00435,MESH:D017202,Nitric Oxide,Myocardial Ischemia
8225,drug,DB00544,528,Fluorouracil,indication,disease,5053,12683,Ischemia,1,MiRAGE,DB00544,MESH:D007511,Fluorouracil,Ischemia
18838,drug,DB00544,528,Fluorouracil,indication,disease,5053,12683,Acute Coronary Syndrome,1,MiRAGE,DB00544,MESH:D054058,Fluorouracil,Acute Coronary Syndrome
3689,drug,DB00571,555,Propranolol,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00571,MESH:D003324,Propranolol,Coronary Artery Disease
17155,drug,DB00571,555,Propranolol,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00571,MESH:D017202,Propranolol,Myocardial Ischemia
3703,drug,DB00584,568,Enalapril,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00584,MESH:D003324,Enalapril,Coronary Artery Disease
17102,drug,DB00584,568,Enalapril,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00584,MESH:D017202,Enalapril,Myocardial Ischemia
8250,drug,DB00598,582,Labetalol,indication,disease,5053,12683,Ischemia,1,MiRAGE,DB00598,MESH:D007511,Labetalol,Ischemia
18828,drug,DB00598,582,Labetalol,indication,disease,5053,12683,Acute Coronary Syndrome,1,MiRAGE,DB00598,MESH:D054058,Labetalol,Acute Coronary Syndrome
3705,drug,DB00622,606,Nicardipine,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00622,MESH:D003324,Nicardipine,Coronary Artery Disease
17107,drug,DB00622,606,Nicardipine,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00622,MESH:D017202,Nicardipine,Myocardial Ischemia
3729,drug,DB00627,611,Niacin,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00627,MESH:D003324,Niacin,Coronary Artery Disease
17131,drug,DB00627,611,Niacin,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00627,MESH:D017202,Niacin,Myocardial Ischemia
3696,drug,DB00661,645,Verapamil,indication,disease,5010,12650,Coronary Artery Disease,1,MiRAGE,DB00661,MESH:D003324,Verapamil,Coronary Artery Disease
17097,drug,DB00661,645,Verapamil,indication,disease,5010,12650,Myocardial Ischemia,1,MiRAGE,DB00661,MESH:D017202,Verapamil,Myocardial Ischemia
8232,drug,DB00669,652,Sumatriptan,indication,disease,5053,12683,Ischemia,1,MiRAGE,DB00669,MESH:D007511,Sumatriptan,Ischemia
18815,drug,DB00669,652,Sumatriptan,indication,disease,5053,12683,Acute Coronary Syndrome,1,MiRAGE,DB00669,MESH:D054058,Sumatriptan,Acute Coronary Syndrome

Duplicate groups summary example:

,x_type,x_idx,relation,y_type,y_idx,n_rows,x_id,y_id,x_name,y_name,original_DiseaseIDs,original_DiseaseNames
0,drug,5,indication,disease,12683,2,DB00006,5053,Bivalirudin,Ischemia,MESH:D007511|MESH:D054058,Acute Coronary Syndrome|Ischemia
19,drug,710,indication,disease,12650,2,DB00727,5010,Nitroglycerin,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
21,drug,740,indication,disease,12650,2,DB00758,5010,Clopidogrel,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
22,drug,822,indication,disease,12650,2,DB00841,5010,Dobutamine,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
23,drug,888,indication,disease,12502,2,DB00907,4849,Cocaine,Emphysema,MESH:D004646|MESH:D011656,Emphysema|Pulmonary Emphysema
24,drug,888,indication,disease,12650,2,DB00907,5010,Cocaine,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
25,drug,888,indication,disease,12683,2,DB00907,5053,Cocaine,Ischemia,MESH:D007511|MESH:D054058,Acute Coronary Syndrome|Ischemia
26,drug,888,indication,disease,12888,2,DB00907,5294,Cocaine,Helicobacter Infections,MESH:D016481|MESH:D016491,Helicobacter Infections|Peripheral Vascular Di...
27,drug,896,indication,disease,13373,2,DB00915,5812,Amantadine,"Influenza, Human",MESH:D007251|MESH:D009976,"Influenza, Human|Orthomyxoviridae Infections"
28,drug,926,indication,disease,12650,2,DB00945,5010,Aspirin,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
29,drug,956,indication,disease,12650,2,DB00975,5010,Dipyridamole,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
30,drug,997,indication,disease,12650,2,DB01016,5010,Glyburide,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
31,drug,1093,indication,disease,12650,2,DB01115,5010,Nifedipine,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
32,drug,1096,indication,disease,12650,2,DB01118,5010,Amiodarone,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
33,drug,1453,indication,disease,12683,2,DB01593,5053,Zinc,Ischemia,MESH:D007511|MESH:D054058,Acute Coronary Syndrome|Ischemia
34,drug,3216,indication,disease,12650,2,DB04880,5010,Enoximone,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
35,drug,5810,indication,disease,12683,2,DB09130,5053,Copper,Ischemia,MESH:D007511|MESH:D054058,Acute Coronary Syndrome|Ischemia
20,drug,710,indication,disease,12683,2,DB00727,5053,Nitroglycerin,Ischemia,MESH:D007511|MESH:D054058,Acute Coronary Syndrome|Ischemia
18,drug,706,indication,disease,12650,2,DB00723,5010,Methoxamine,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia
1,drug,252,indication,disease,12650,2,DB00264,5010,Metoprolol,Coronary Artery Disease,MESH:D003324|MESH:D017202,Coronary Artery Disease|Myocardial Ischemia

TxGNN external positive edge table summary after dedup:
Raw positive rows: 19,790
Deduplicated positive edges: 19,753
Removed duplicate rows: 37

Relation distribution:
relation
indication    19753
Name: count, dtype: int64

Unique counts after dedup:
Unique drugs: 1303
Unique diseases: 844
Unique drug-disease edges: 19753

Deduplicated edge table head:

,x_type,x_id,x_idx,x_name,relation,y_type,y_id,y_idx,y_name,label,source,original_DrugID,original_DiseaseID,original_DrugName,original_DiseaseName
0,drug,DB09140,5819,Oxygen,indication,disease,839,15671,Congenital Abnormalities,1,MiRAGE,DB09140,MESH:D000013,Oxygen,Congenital Abnormalities
1,drug,DB00730,712,Thiabendazole,indication,disease,839,15671,Congenital Abnormalities,1,MiRAGE,DB00730,MESH:D000013,Thiabendazole,Congenital Abnormalities
2,drug,DB00898,879,Ethanol,indication,disease,839,15671,Congenital Abnormalities,1,MiRAGE,DB00898,MESH:D000013,Ethanol,Congenital Abnormalities
3,drug,DB01168,1145,Procarbazine,indication,disease,839,15671,Congenital Abnormalities,1,MiRAGE,DB01168,MESH:D000013,Procarbazine,Congenital Abnormalities
4,drug,DB00550,534,Propylthiouracil,indication,disease,839,15671,Congenital Abnormalities,1,MiRAGE,DB00550,MESH:D000013,Propylthiouracil,Congenital Abnormalities

Duplicated TxGNN positive edges after dedup: 0

Sanity checks passed.

In [14]:
# ============================================================
# 14. Save final minimal outputs
# ============================================================

# Add TxGNN local indices back to graph-present unseen table for final output.
# This preserves the final de-leaked graph-present MiRAGE rows while also
# making the file directly usable for TxGNN/GNN evaluation.
mirage_graph_present_final = txgnn_graph_present_evaluable.copy()

# Graph-unpresent / graph-absent final output.
mirage_graph_unpresent_final = mirage_graph_absent_unseen.copy()

# Final output paths
mirage_graph_present_path = OUTPUT_DIR / "mirage_graph_present.csv"
mirage_graph_unpresent_path = OUTPUT_DIR / "mirage_graph_unpresent.csv"

# Save only final CSV outputs
mirage_graph_present_final.to_csv(mirage_graph_present_path, index=False)
mirage_graph_unpresent_final.to_csv(mirage_graph_unpresent_path, index=False)

# ============================================================
# Update summary JSON with TxGNN-specific counts
# ============================================================

# summary_json_path and summary are created in Cell 11.
summary.update({
    "graph_present_final_csv": str(mirage_graph_present_path),
    "graph_unpresent_final_csv": str(mirage_graph_unpresent_path),

    "graph_present_final_rows": int(len(mirage_graph_present_final)),
    "graph_unpresent_final_rows": int(len(mirage_graph_unpresent_final)),

    "txgnn_graph_present_unseen_raw_rows": int(len(txgnn_external_test_positive_edges_raw)),
    "txgnn_external_positive_edges_deduplicated": int(len(txgnn_external_test_positive_edges)),
    "txgnn_duplicate_edge_rows": int(len(txgnn_external_test_duplicate_edges)),
    "txgnn_duplicate_extra_rows_removed": int(
        len(txgnn_external_test_positive_edges_raw)
        - len(txgnn_external_test_positive_edges)
    ),
    "txgnn_unique_drugs_in_external_positive_edges": int(
        txgnn_external_test_positive_edges["x_id"].nunique()
    ),
    "txgnn_unique_diseases_in_external_positive_edges": int(
        txgnn_external_test_positive_edges["y_id"].nunique()
    ),
    "txgnn_relation_for_external_positive_edges": DEFAULT_EXTERNAL_RELATION,
    "txgnn_positive_edge_table_note": (
        "MiRAGE is positive-only. The notebook constructs deduplicated positive "
        "drug-disease edges in memory for TxGNN/GNN evaluation, but does not save "
        "a separate TxGNN edge CSV. No negative edges were sampled."
    ),
})

with open(summary_json_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)

print("Saved final minimal outputs:")
print(f"- Summary JSON:           {summary_json_path}")
print(f"- Graph-present CSV:      {mirage_graph_present_path}")
print(f"- Graph-unpresent CSV:    {mirage_graph_unpresent_path}")

print("\nFinal file shapes:")
print(f"mirage_graph_present.csv:   {mirage_graph_present_final.shape}")
print(f"mirage_graph_unpresent.csv: {mirage_graph_unpresent_final.shape}")

print("\nUpdated summary excerpt:")
summary_keys_to_show = [
    "graph_present_final_rows",
    "graph_unpresent_final_rows",
    "txgnn_graph_present_unseen_raw_rows",
    "txgnn_external_positive_edges_deduplicated",
    "txgnn_duplicate_edge_rows",
    "txgnn_duplicate_extra_rows_removed",
    "txgnn_unique_drugs_in_external_positive_edges",
    "txgnn_unique_diseases_in_external_positive_edges",
    "txgnn_relation_for_external_positive_edges",
]
print(json.dumps({k: summary.get(k) for k in summary_keys_to_show}, ensure_ascii=False, indent=2))

Saved final minimal outputs:
- Summary JSON:           ..\data\processed\summary.json
- Graph-present CSV:      ..\data\processed\mirage_graph_present.csv
- Graph-unpresent CSV:    ..\data\processed\mirage_graph_unpresent.csv

Final file shapes:
mirage_graph_present.csv:   (19790, 40)
mirage_graph_unpresent.csv: (19196, 38)

Updated summary excerpt:
{
  "graph_present_final_rows": 19790,
  "graph_unpresent_final_rows": 19196,
  "txgnn_graph_present_unseen_raw_rows": 19790,
  "txgnn_external_positive_edges_deduplicated": 19753,
  "txgnn_duplicate_edge_rows": 74,
  "txgnn_duplicate_extra_rows_removed": 37,
  "txgnn_unique_drugs_in_external_positive_edges": 1303,
  "txgnn_unique_diseases_in_external_positive_edges": 844,
  "txgnn_relation_for_external_positive_edges": "indication"
}

In [15]:
# ============================================================
# 15. Prepare fixed negative sampling settings and candidate pools
# ============================================================
# Goal:
# - Keep the base files already saved by previous cells:
#     summary.json
#     mirage_graph_present.csv
#     mirage_graph_unpresent.csv
# - Do NOT save anything in this cell.
# - Prepare ratios, seeds, candidate pools, degree tables, and forbidden sets
#   for generating 45 fixed positive-negative test sets later.

# ------------------------------------------------------------
# 15.1 Fixed negative sampling design
# ------------------------------------------------------------

NEGATIVE_RATIOS = [1, 4, 9]  # positive:negative = 1:1, 1:4, 1:9
NEGATIVE_SAMPLING_SEEDS = [7, 42, 999, 1443, 2026]

# Concrete subsets:
#   graph_present normal          : 3 ratios × 5 seeds = 15
#   graph_present degree_matched  : 3 ratios × 5 seeds = 15
#   graph_unpresent normal        : 3 ratios × 5 seeds = 15
# Total = 45 fixed test sets.
GRAPH_PRESENT_STRATEGIES = ["normal", "degree_matched"]
GRAPH_UNPRESENT_STRATEGIES = ["normal"]

expected_test_config_count = len(NEGATIVE_RATIOS) * len(NEGATIVE_SAMPLING_SEEDS)
expected_concrete_subset_count = (
    expected_test_config_count
    * (len(GRAPH_PRESENT_STRATEGIES) + len(GRAPH_UNPRESENT_STRATEGIES))
)

print("Fixed negative sampling design:")
print(f"Negative ratios: {NEGATIVE_RATIOS}")
print(f"Random seeds:    {NEGATIVE_SAMPLING_SEEDS}")
print(f"Ratio × seed configurations: {expected_test_config_count}")
print(f"Concrete test subsets:       {expected_concrete_subset_count}")


# ------------------------------------------------------------
# 15.2 Prepare positive base sets
# ------------------------------------------------------------

# Graph-present positives should use the TxGNN-index-enriched dataframe if available.
# This keeps the later graph-present test sets directly usable for GNN/TxGNN evaluation.
if "txgnn_graph_present_evaluable" in globals():
    graph_present_pos_base = txgnn_graph_present_evaluable.copy().reset_index(drop=True)
else:
    graph_present_pos_base = mirage_graph_present_unseen.copy().reset_index(drop=True)

graph_present_pos_base["graph_group"] = "graph_present"
graph_present_pos_base["label"] = 1
graph_present_pos_base["sample_type"] = "positive"

if "txgnn_drug_idx" in graph_present_pos_base.columns:
    graph_present_pos_base["txgnn_drug_idx"] = graph_present_pos_base["txgnn_drug_idx"].astype(int)

if "txgnn_disease_idx" in graph_present_pos_base.columns:
    graph_present_pos_base["txgnn_disease_idx"] = graph_present_pos_base["txgnn_disease_idx"].astype(int)


graph_unpresent_pos_base = mirage_graph_absent_unseen.copy().reset_index(drop=True)
graph_unpresent_pos_base["graph_group"] = "graph_unpresent"
graph_unpresent_pos_base["label"] = 1
graph_unpresent_pos_base["sample_type"] = "positive"

print("\nPositive base sets:")
print(f"Graph-present positives:   {len(graph_present_pos_base):,}")
print(f"Graph-unpresent positives: {len(graph_unpresent_pos_base):,}")


# ------------------------------------------------------------
# 15.3 Candidate drug pools
# ------------------------------------------------------------
# Graph-present:
#   replacement drugs must be in PrimeKG / TxGNN local index map.
# Graph-unpresent:
#   replacement drugs can be any MiRAGE drug with text fields.
# ------------------------------------------------------------

graph_present_drug_candidates = (
    mirage.loc[
        mirage["drug_in_primekg"],
        ["DrugID", "DrugName", "primekg_drug_node_id", "primekg_drug_node_name"]
    ]
    .drop_duplicates(subset=["DrugID"])
    .copy()
)

graph_present_drug_candidates["DrugID"] = graph_present_drug_candidates["DrugID"].apply(
    canonical_drugbank_id
)
graph_present_drug_candidates["primekg_drug_node_id"] = graph_present_drug_candidates[
    "primekg_drug_node_id"
].apply(normalize_primekg_node_id)

# Add TxGNN local drug index if maps from previous cells are available.
if "txgnn_drug_id_to_local_idx" in globals():
    graph_present_drug_candidates["txgnn_drug_idx"] = graph_present_drug_candidates[
        "primekg_drug_node_id"
    ].map(txgnn_drug_id_to_local_idx)
else:
    graph_present_drug_candidates["txgnn_drug_idx"] = pd.NA

graph_present_drug_candidates = (
    graph_present_drug_candidates
    .dropna(subset=["DrugID", "DrugName", "primekg_drug_node_id"])
    .copy()
    .reset_index(drop=True)
)

# If TxGNN local indices exist, require them for graph-present GNN-compatible negatives.
if "txgnn_drug_id_to_local_idx" in globals():
    graph_present_drug_candidates = (
        graph_present_drug_candidates
        .dropna(subset=["txgnn_drug_idx"])
        .copy()
        .reset_index(drop=True)
    )
    graph_present_drug_candidates["txgnn_drug_idx"] = graph_present_drug_candidates[
        "txgnn_drug_idx"
    ].astype(int)


graph_unpresent_drug_candidates = (
    mirage[
        [
            "DrugID",
            "DrugName",
            "primekg_drug_node_id",
            "drug_in_primekg",
        ]
    ]
    .drop_duplicates(subset=["DrugID"])
    .copy()
    .reset_index(drop=True)
)

graph_unpresent_drug_candidates["DrugID"] = graph_unpresent_drug_candidates["DrugID"].apply(
    canonical_drugbank_id
)
graph_unpresent_drug_candidates["primekg_drug_node_id"] = graph_unpresent_drug_candidates[
    "primekg_drug_node_id"
].apply(normalize_primekg_node_id)

print("\nCandidate drug pools:")
print(f"Graph-present candidate drugs:   {len(graph_present_drug_candidates):,}")
print(f"Graph-unpresent candidate drugs: {len(graph_unpresent_drug_candidates):,}")


# ------------------------------------------------------------
# 15.4 Compute PrimeKG / TxGNN drug degrees for degree-matched sampling
# ------------------------------------------------------------

def build_node_degree_table_from_kg_directed(kg_directed_df):
    """
    Compute node degree from directed KG edges by counting appearances
    on both x-side and y-side.
    """
    x_deg = (
        kg_directed_df[["x_type", "x_id"]]
        .rename(columns={"x_type": "node_type", "x_id": "node_id"})
        .copy()
    )
    y_deg = (
        kg_directed_df[["y_type", "y_id"]]
        .rename(columns={"y_type": "node_type", "y_id": "node_id"})
        .copy()
    )

    deg = pd.concat([x_deg, y_deg], ignore_index=True)
    deg["node_type"] = deg["node_type"].astype(str)
    deg["node_id"] = deg["node_id"].apply(normalize_primekg_node_id)

    deg = (
        deg
        .groupby(["node_type", "node_id"])
        .size()
        .reset_index(name="degree")
    )

    return deg


assert "kg_directed" in globals(), (
    "kg_directed is not available. Please run the TxGNN local-index cell first."
)

node_degree_df = build_node_degree_table_from_kg_directed(kg_directed)

drug_degree_df = (
    node_degree_df[node_degree_df["node_type"] == "drug"][["node_id", "degree"]]
    .rename(columns={"node_id": "primekg_drug_node_id", "degree": "drug_degree"})
    .copy()
)

graph_present_drug_candidates = graph_present_drug_candidates.merge(
    drug_degree_df,
    on="primekg_drug_node_id",
    how="left",
)

graph_present_drug_candidates["drug_degree"] = (
    graph_present_drug_candidates["drug_degree"]
    .fillna(0)
    .astype(int)
)

drug_degree_lookup = dict(
    zip(
        graph_present_drug_candidates["primekg_drug_node_id"],
        graph_present_drug_candidates["drug_degree"],
    )
)

graph_present_pos_base["positive_drug_degree"] = (
    graph_present_pos_base["primekg_drug_node_id"]
    .apply(normalize_primekg_node_id)
    .map(drug_degree_lookup)
    .fillna(0)
    .astype(int)
)

print("\nGraph-present candidate drug degree summary:")
display(graph_present_drug_candidates["drug_degree"].describe())

print("\nPositive graph-present drug degree summary:")
display(graph_present_pos_base["positive_drug_degree"].describe())


# ------------------------------------------------------------
# 15.5 Forbidden positive / leakage pair sets
# ------------------------------------------------------------
# These sets are used later to ensure sampled negatives are not known positives.
#
# For graph-present negatives:
#   - forbid by PrimeKG graph identity: (primekg_drug_node_id, primekg_disease_node_id)
#
# For graph-unpresent negatives:
#   - forbid by original MiRAGE identity: (DrugID, DiseaseID)
#   - forbid by conservative name identity: (DrugID, normalized DiseaseName)
#
# For both:
#   - forbid raw LLM train-source overlap: (DrugBank ID, normalized disease name)
#   - forbid PrimeKG known DD relations whenever both endpoints are mappable.

# 1) MiRAGE full positives by original IDs.
# Used mainly for graph-unpresent negatives.
mirage_original_positive_pairs = set(
    zip(
        mirage["DrugID"].apply(canonical_drugbank_id),
        mirage["DiseaseID"].astype(str),
    )
)

# 2) MiRAGE full positives by DrugBank ID + normalized disease name.
# This is important because graph-unpresent diseases may not have graph IDs,
# but the same disease can appear under name-level identity.
mirage_name_positive_pairs = set(
    zip(
        mirage["DrugID"].apply(canonical_drugbank_id),
        mirage["DiseaseName"].apply(normalize_text),
    )
)

# 3) MiRAGE graph-present positives by PrimeKG node IDs, including all MiRAGE rows
# that are graph-present before exclusion.
mirage_graph_present_positive_graph_pairs_all = set(
    zip(
        mirage.loc[mirage["graph_present"], "primekg_drug_node_id"].apply(normalize_primekg_node_id),
        mirage.loc[mirage["graph_present"], "primekg_disease_node_id"].apply(normalize_primekg_node_id),
    )
)

# 4) Current final graph-present positive base by PrimeKG node IDs.
# This explicitly protects the de-leaked evaluation positives.
graph_present_base_positive_graph_pairs = set(
    zip(
        graph_present_pos_base["primekg_drug_node_id"].apply(normalize_primekg_node_id),
        graph_present_pos_base["primekg_disease_node_id"].apply(normalize_primekg_node_id),
    )
)

# 5) Current final graph-unpresent positive base by original ID and name.
graph_unpresent_base_positive_original_pairs = set(
    zip(
        graph_unpresent_pos_base["DrugID"].apply(canonical_drugbank_id),
        graph_unpresent_pos_base["DiseaseID"].astype(str),
    )
)

graph_unpresent_base_positive_name_pairs = set(
    zip(
        graph_unpresent_pos_base["DrugID"].apply(canonical_drugbank_id),
        graph_unpresent_pos_base["DiseaseName"].apply(normalize_text),
    )
)

# 6) PrimeKG known DD pairs from previous overlap step.
assert "primekg_known_dd_pairs" in globals(), (
    "primekg_known_dd_pairs is not available. Please run the PrimeKG overlap cell first."
)

primekg_forbidden_graph_pairs = set(primekg_known_dd_pairs)

# 7) Union for graph-present negatives.
# Any sampled graph-present negative pair in this set must be rejected.
graph_present_forbidden_graph_pairs = (
    mirage_graph_present_positive_graph_pairs_all
    | graph_present_base_positive_graph_pairs
    | primekg_forbidden_graph_pairs
)

# 8) Union for graph-unpresent negatives.
# Any sampled graph-unpresent negative original/name pair in these sets must be rejected.
graph_unpresent_forbidden_original_pairs = (
    mirage_original_positive_pairs
    | graph_unpresent_base_positive_original_pairs
)

graph_unpresent_forbidden_name_pairs = (
    mirage_name_positive_pairs
    | graph_unpresent_base_positive_name_pairs
)

# 9) Raw LLM train-source pair sources from previous overlap step.
assert "train_source_name_pair_sources" in globals(), (
    "train_source_name_pair_sources is not available. Please run the raw train-source overlap cell first."
)

def is_train_source_overlap(drug_id, disease_name):
    """
    Conservative LLM training-source overlap check:
    DrugBank ID exact match + normalized disease-name exact match.
    """
    key = (
        canonical_drugbank_id(drug_id),
        normalize_text(disease_name),
    )
    return key in train_source_name_pair_sources


print("\nForbidden / leakage-control sets:")
print(f"MiRAGE original positive pairs:                  {len(mirage_original_positive_pairs):,}")
print(f"MiRAGE name positive pairs:                      {len(mirage_name_positive_pairs):,}")
print(f"MiRAGE graph-present graph pairs all:            {len(mirage_graph_present_positive_graph_pairs_all):,}")
print(f"Graph-present base positive graph pairs:         {len(graph_present_base_positive_graph_pairs):,}")
print(f"PrimeKG known DD graph pairs:                    {len(primekg_forbidden_graph_pairs):,}")
print(f"Graph-present forbidden graph union:             {len(graph_present_forbidden_graph_pairs):,}")
print(f"Graph-unpresent forbidden original-pair union:   {len(graph_unpresent_forbidden_original_pairs):,}")
print(f"Graph-unpresent forbidden name-pair union:       {len(graph_unpresent_forbidden_name_pairs):,}")
print(f"Raw LLM train-source pair keys:                  {len(train_source_name_pair_sources):,}")

# Optional sanity: final positives must be covered by the forbidden sets.
assert graph_present_base_positive_graph_pairs.issubset(graph_present_forbidden_graph_pairs)
assert graph_unpresent_base_positive_original_pairs.issubset(graph_unpresent_forbidden_original_pairs)
assert graph_unpresent_base_positive_name_pairs.issubset(graph_unpresent_forbidden_name_pairs)

print("\nForbidden-set sanity checks passed.")


# ------------------------------------------------------------
# 15.6 Sanity checks
# ------------------------------------------------------------

assert len(NEGATIVE_RATIOS) == 3
assert len(NEGATIVE_SAMPLING_SEEDS) == 5
assert expected_test_config_count == 15
assert expected_concrete_subset_count == 45

assert len(graph_present_pos_base) > 0
assert len(graph_unpresent_pos_base) > 0
assert len(graph_present_drug_candidates) > 0
assert len(graph_unpresent_drug_candidates) > 0

assert graph_present_pos_base["label"].eq(1).all()
assert graph_unpresent_pos_base["label"].eq(1).all()

print("\nNegative sampling preparation completed.")

Fixed negative sampling design:
Negative ratios: [1, 4, 9]
Random seeds:    [7, 42, 999, 1443, 2026]
Ratio × seed configurations: 15
Concrete test subsets:       45

Positive base sets:
Graph-present positives:   19,790
Graph-unpresent positives: 19,196

Candidate drug pools:
Graph-present candidate drugs:   1,408
Graph-unpresent candidate drugs: 1,410

Graph-present candidate drug degree summary:

count    1408.000000
mean      990.785511
std       614.301559
min         1.000000
25%       500.750000
50%       990.000000
75%      1458.500000
max      2600.000000
Name: drug_degree, dtype: float64

Positive graph-present drug degree summary:

count    19790.000000
mean      1291.978070
std        613.714296
min          1.000000
25%        872.000000
50%       1353.000000
75%       1733.000000
max       2600.000000
Name: positive_drug_degree, dtype: float64

Forbidden / leakage-control sets:
MiRAGE original positive pairs:                  42,200
MiRAGE name positive pairs:                      42,200
MiRAGE graph-present graph pairs all:            22,559
Graph-present base positive graph pairs:         19,753
PrimeKG known DD graph pairs:                    42,383
Graph-present forbidden graph union:             62,272
Graph-unpresent forbidden original-pair union:   42,200
Graph-unpresent forbidden name-pair union:       42,200
Raw LLM train-source pair keys:                  10,895

Forbidden-set sanity checks passed.

Negative sampling preparation completed.

In [16]:
# ============================================================
# 16. Generate / load fixed negative samples for 45 test subsets
#     Fast version with checkpoint / resume
# ============================================================
# This cell is compatible with already-generated subset files:
# - Existing CSVs in OUTPUT_DIR / "fixed_test_sets" are loaded and reused.
# - Missing CSVs are generated with a faster disease-level candidate cache.
#
# Output directory:
#   OUTPUT_DIR / "fixed_test_sets"
#
# File naming:
#   {dataset}__{graph_group}__{sampling_strategy}__ratio_{ratio}__seed_{seed}.csv
#
# Generated subsets:
#   graph_present normal          : 3 ratios × 5 seeds = 15
#   graph_present degree_matched  : 3 ratios × 5 seeds = 15
#   graph_unpresent normal        : 3 ratios × 5 seeds = 15
# Total = 45 concrete test subsets.
#
# Notes:
# - This implementation enforces negative uniqueness within each positive row,
#   not globally across the subset.
# - This implementation does NOT require GPU. It speeds up sampling by caching
#   valid candidate drugs per disease.

# ------------------------------------------------------------
# 16.0 Checkpoint / resume settings
# ------------------------------------------------------------

FIXED_TEST_SET_DIR = OUTPUT_DIR / "fixed_test_sets"
FIXED_TEST_SET_DIR.mkdir(parents=True, exist_ok=True)

FIXED_TEST_SET_DATASET_NAME = "mirage"

# If False, existing subset files are loaded and skipped.
# If True, all subset files are regenerated and overwritten.
OVERWRITE_FIXED_TEST_SETS = False

fixed_test_manifest_path = FIXED_TEST_SET_DIR / "manifest.csv"

print("Fixed test-set checkpoint directory:")
print(FIXED_TEST_SET_DIR.resolve())
print(f"Overwrite existing subset files: {OVERWRITE_FIXED_TEST_SETS}")


def fixed_test_set_filename(graph_group, sampling_strategy, negative_ratio, seed):
    return (
        f"{FIXED_TEST_SET_DATASET_NAME}"
        f"__{graph_group}"
        f"__{sampling_strategy}"
        f"__ratio_{int(negative_ratio)}"
        f"__seed_{int(seed)}"
        f".csv"
    )


def fixed_test_set_path(graph_group, sampling_strategy, negative_ratio, seed):
    return FIXED_TEST_SET_DIR / fixed_test_set_filename(
        graph_group=graph_group,
        sampling_strategy=sampling_strategy,
        negative_ratio=negative_ratio,
        seed=seed,
    )


# ------------------------------------------------------------
# 16.1 Precompute normalized candidate columns
# ------------------------------------------------------------
# These columns are added only if missing, so this cell remains compatible
# with the previous preparation cell.

graph_present_drug_candidates = graph_present_drug_candidates.copy().reset_index(drop=True)
graph_unpresent_drug_candidates = graph_unpresent_drug_candidates.copy().reset_index(drop=True)

if "drug_id_norm" not in graph_present_drug_candidates.columns:
    graph_present_drug_candidates["drug_id_norm"] = graph_present_drug_candidates["DrugID"].apply(
        canonical_drugbank_id
    )

if "drug_node_id_norm" not in graph_present_drug_candidates.columns:
    graph_present_drug_candidates["drug_node_id_norm"] = graph_present_drug_candidates[
        "primekg_drug_node_id"
    ].apply(normalize_primekg_node_id)

if "drug_id_norm" not in graph_unpresent_drug_candidates.columns:
    graph_unpresent_drug_candidates["drug_id_norm"] = graph_unpresent_drug_candidates["DrugID"].apply(
        canonical_drugbank_id
    )

if "drug_node_id_norm" not in graph_unpresent_drug_candidates.columns:
    graph_unpresent_drug_candidates["drug_node_id_norm"] = graph_unpresent_drug_candidates[
        "primekg_drug_node_id"
    ].apply(normalize_primekg_node_id)

# Make sure degree exists for graph-present degree matching.
if "drug_degree" not in graph_present_drug_candidates.columns:
    graph_present_drug_candidates["drug_degree"] = 0

graph_present_drug_candidates["drug_degree"] = (
    pd.to_numeric(graph_present_drug_candidates["drug_degree"], errors="coerce")
    .fillna(0)
    .astype(int)
)

print("\nCandidate pools after normalization:")
print(f"Graph-present candidates:   {len(graph_present_drug_candidates):,}")
print(f"Graph-unpresent candidates: {len(graph_unpresent_drug_candidates):,}")


# ------------------------------------------------------------
# 16.2 Disease-level valid candidate caches
# ------------------------------------------------------------

graph_present_valid_candidate_cache = {}
graph_unpresent_valid_candidate_cache = {}


def get_graph_present_valid_candidates_for_disease(disease_node_id, disease_name):
    """
    Return valid graph-present negative drug candidates for a fixed disease.
    Cache key is disease graph node + normalized disease name.

    Filters:
    - Not in graph_present_forbidden_graph_pairs.
    - Not overlapping raw LLM train-source pairs.
    """
    disease_node_id = normalize_primekg_node_id(disease_node_id)
    disease_name_norm = normalize_text(disease_name)
    cache_key = (disease_node_id, disease_name_norm)

    if cache_key in graph_present_valid_candidate_cache:
        return graph_present_valid_candidate_cache[cache_key]

    df = graph_present_drug_candidates.copy()

    # For this fixed disease, each candidate forms one graph pair.
    df["candidate_graph_pair"] = list(
        zip(
            df["drug_node_id_norm"],
            [disease_node_id] * len(df),
        )
    )

    # Fast train-source overlap check using pre-normalized drug ID.
    df["train_source_overlap"] = [
        (drug_id, disease_name_norm) in train_source_name_pair_sources
        for drug_id in df["drug_id_norm"]
    ]

    df = df[
        ~df["candidate_graph_pair"].isin(graph_present_forbidden_graph_pairs)
        & ~df["train_source_overlap"]
    ].copy()

    df = df.reset_index(drop=True)

    graph_present_valid_candidate_cache[cache_key] = df
    return df


def get_graph_unpresent_valid_candidates_for_disease(
    disease_id,
    disease_name,
    disease_in_primekg,
    disease_node_id,
):
    """
    Return valid graph-unpresent / cold-start negative drug candidates
    for a fixed disease.

    Filters:
    - Not in graph_unpresent_forbidden_original_pairs.
    - Not in graph_unpresent_forbidden_name_pairs.
    - Not overlapping raw LLM train-source pairs.
    - If both endpoints are graph-mappable, not in PrimeKG known DD pairs.
    """
    disease_id = str(disease_id)
    disease_name_norm = normalize_text(disease_name)
    disease_node_id = normalize_primekg_node_id(disease_node_id)
    disease_in_primekg = bool(disease_in_primekg)

    cache_key = (
        disease_id,
        disease_name_norm,
        disease_in_primekg,
        disease_node_id,
    )

    if cache_key in graph_unpresent_valid_candidate_cache:
        return graph_unpresent_valid_candidate_cache[cache_key]

    df = graph_unpresent_drug_candidates.copy()

    df["candidate_original_pair"] = list(
        zip(
            df["drug_id_norm"],
            [disease_id] * len(df),
        )
    )

    df["candidate_name_pair"] = list(
        zip(
            df["drug_id_norm"],
            [disease_name_norm] * len(df),
        )
    )

    df["train_source_overlap"] = [
        (drug_id, disease_name_norm) in train_source_name_pair_sources
        for drug_id in df["drug_id_norm"]
    ]

    valid_mask = (
        ~df["candidate_original_pair"].isin(graph_unpresent_forbidden_original_pairs)
        & ~df["candidate_name_pair"].isin(graph_unpresent_forbidden_name_pairs)
        & ~df["train_source_overlap"]
    )

    if disease_in_primekg:
        # Reject PrimeKG known DD only for candidate drugs that are also graph-mappable.
        df["candidate_graph_pair"] = list(
            zip(
                df["drug_node_id_norm"],
                [disease_node_id] * len(df),
            )
        )

        graph_known_mask = (
            df["drug_in_primekg"].fillna(False).astype(bool)
            & df["candidate_graph_pair"].isin(primekg_forbidden_graph_pairs)
        )

        valid_mask = valid_mask & ~graph_known_mask

    df = df[valid_mask].copy().reset_index(drop=True)

    graph_unpresent_valid_candidate_cache[cache_key] = df
    return df


# ------------------------------------------------------------
# 16.3 Helper functions
# ------------------------------------------------------------

def make_positive_subset(pos_df, graph_group, sampling_strategy, negative_ratio, seed):
    """
    Create the positive part for one fixed test subset.
    Positive rows are repeated per ratio/seed/strategy so every saved test subset
    is self-contained.
    """
    out = pos_df.copy().reset_index(drop=True)

    out["graph_group"] = graph_group
    out["negative_sampling_strategy"] = sampling_strategy
    out["negative_ratio"] = int(negative_ratio)
    out["negative_sampling_seed"] = int(seed)
    out["test_config_id"] = f"ratio{negative_ratio}_seed{seed}"
    out["test_subset_id"] = f"{graph_group}_{sampling_strategy}_ratio{negative_ratio}_seed{seed}"

    out["sample_type"] = "positive"
    out["label"] = 1

    # Positive row index within the base positive dataframe.
    out["positive_row_index"] = np.arange(len(out), dtype=int)

    # Fill negative-specific columns for schema consistency.
    if "matched_positive_drug_degree" not in out.columns:
        out["matched_positive_drug_degree"] = pd.NA
    if "negative_drug_degree" not in out.columns:
        out["negative_drug_degree"] = pd.NA
    if "degree_abs_diff" not in out.columns:
        out["degree_abs_diff"] = pd.NA

    return out


def add_common_negative_metadata(neg, graph_group, sampling_strategy, negative_ratio, seed, positive_row_index):
    """
    Add common metadata fields to one sampled negative row.
    """
    neg["graph_group"] = graph_group
    neg["negative_sampling_strategy"] = sampling_strategy
    neg["negative_ratio"] = int(negative_ratio)
    neg["negative_sampling_seed"] = int(seed)
    neg["test_config_id"] = f"ratio{negative_ratio}_seed{seed}"
    neg["test_subset_id"] = f"{graph_group}_{sampling_strategy}_ratio{negative_ratio}_seed{seed}"

    neg["sample_type"] = "negative"
    neg["label"] = 0
    neg["positive_row_index"] = int(positive_row_index)

    return neg


def make_negative_from_graph_present_candidate(pos_row, cand, graph_group, strategy, ratio, seed, pos_i):
    """
    Build one graph-present negative row from a candidate drug.
    """
    neg = pos_row.copy()

    neg["DrugID"] = cand["drug_id_norm"]
    neg["DrugName"] = cand["DrugName"]
    neg["primekg_drug_node_id"] = cand["drug_node_id_norm"]
    neg["primekg_drug_node_name"] = cand.get(
        "primekg_drug_node_name",
        cand["DrugName"],
    )

    if "txgnn_drug_idx" in cand.index and not pd.isna(cand["txgnn_drug_idx"]):
        neg["txgnn_drug_idx"] = int(cand["txgnn_drug_idx"])

    neg = add_common_negative_metadata(
        neg,
        graph_group=graph_group,
        sampling_strategy=strategy,
        negative_ratio=ratio,
        seed=seed,
        positive_row_index=pos_i,
    )

    pos_degree = int(pos_row.get("positive_drug_degree", 0))
    neg_degree = int(cand.get("drug_degree", 0))

    neg["matched_positive_drug_degree"] = pos_degree
    neg["negative_drug_degree"] = neg_degree
    neg["degree_abs_diff"] = abs(pos_degree - neg_degree)

    return neg


def make_negative_from_graph_unpresent_candidate(pos_row, cand, graph_group, strategy, ratio, seed, pos_i):
    """
    Build one graph-unpresent negative row from a candidate drug.
    """
    neg = pos_row.copy()

    neg["DrugID"] = cand["drug_id_norm"]
    neg["DrugName"] = cand["DrugName"]
    neg["primekg_drug_node_id"] = cand["drug_node_id_norm"]
    neg["drug_in_primekg"] = bool(cand.get("drug_in_primekg", False))

    neg = add_common_negative_metadata(
        neg,
        graph_group=graph_group,
        sampling_strategy=strategy,
        negative_ratio=ratio,
        seed=seed,
        positive_row_index=pos_i,
    )

    neg["matched_positive_drug_degree"] = pd.NA
    neg["negative_drug_degree"] = pd.NA
    neg["degree_abs_diff"] = pd.NA

    return neg


def sample_graph_present_negatives_normal(pos_df, negative_ratio, seed):
    """
    Fast graph-present normal negative sampling:
    - Per disease, valid candidates are cached once.
    - For each positive row, sample negative_ratio candidates without replacement
      from that disease's valid candidate pool.
    """
    rng = np.random.default_rng(seed)
    negative_rows = []

    for pos_i, pos_row in tqdm(
        pos_df.iterrows(),
        total=len(pos_df),
        desc=f"GP normal negatives | ratio={negative_ratio}, seed={seed}",
    ):
        disease_node_id = normalize_primekg_node_id(pos_row["primekg_disease_node_id"])
        disease_name = pos_row["DiseaseName"]

        valid = get_graph_present_valid_candidates_for_disease(
            disease_node_id=disease_node_id,
            disease_name=disease_name,
        )

        if len(valid) < negative_ratio:
            raise RuntimeError(
                f"Not enough graph-present valid negative candidates for one positive row. "
                f"pos_i={pos_i}, DiseaseID={pos_row.get('DiseaseID')}, "
                f"DiseaseName={disease_name}, available={len(valid)}, "
                f"required={negative_ratio}, seed={seed}."
            )

        chosen_idx = rng.choice(len(valid), size=negative_ratio, replace=False)

        for idx in chosen_idx:
            cand = valid.iloc[int(idx)]
            neg = make_negative_from_graph_present_candidate(
                pos_row=pos_row,
                cand=cand,
                graph_group="graph_present",
                strategy="normal",
                ratio=negative_ratio,
                seed=seed,
                pos_i=pos_i,
            )
            negative_rows.append(neg)

    return pd.DataFrame(negative_rows).reset_index(drop=True)


def sample_graph_present_negatives_degree_matched(pos_df, negative_ratio, seed):
    """
    Fast graph-present degree-matched negative sampling:
    - Per disease, valid candidates are cached once.
    - For each positive row, choose candidates whose drug degree is closest to
      the positive drug degree.
    - Ties are randomized with the fixed RNG seed.
    """
    rng = np.random.default_rng(seed)
    negative_rows = []

    for pos_i, pos_row in tqdm(
        pos_df.iterrows(),
        total=len(pos_df),
        desc=f"GP degree-matched negatives | ratio={negative_ratio}, seed={seed}",
    ):
        disease_node_id = normalize_primekg_node_id(pos_row["primekg_disease_node_id"])
        disease_name = pos_row["DiseaseName"]
        target_degree = int(pos_row.get("positive_drug_degree", 0))

        valid = get_graph_present_valid_candidates_for_disease(
            disease_node_id=disease_node_id,
            disease_name=disease_name,
        )

        if len(valid) < negative_ratio:
            raise RuntimeError(
                f"Not enough graph-present valid degree-matched candidates for one positive row. "
                f"pos_i={pos_i}, DiseaseID={pos_row.get('DiseaseID')}, "
                f"DiseaseName={disease_name}, available={len(valid)}, "
                f"required={negative_ratio}, seed={seed}."
            )

        # Compute distance once for this positive row.
        degree_diff = (valid["drug_degree"].astype(int).to_numpy() - target_degree)
        abs_diff = np.abs(degree_diff)

        # Pick all candidates whose degree distance is among the closest values.
        # We use a stable partial ordering and randomize within ties / selected region.
        order = np.argsort(abs_diff, kind="stable")

        # To avoid deterministic always-same picks in exact ties, take a small window
        # around the closest candidates, then choose the best negative_ratio after
        # tie-aware shuffling.
        window_size = min(max(negative_ratio * 10, negative_ratio), len(order))
        window_idx = order[:window_size]

        # Sort window by abs diff, but randomize within equal-diff groups.
        window_df = valid.iloc[window_idx].copy()
        window_df["_degree_abs_diff_tmp"] = abs_diff[window_idx]

        chosen_rows = []

        for diff_value, tie_group in window_df.groupby("_degree_abs_diff_tmp", sort=True):
            tie_group = tie_group.sample(
                frac=1,
                random_state=int(rng.integers(0, 2**31 - 1)),
            )

            for _, cand in tie_group.iterrows():
                chosen_rows.append(cand)
                if len(chosen_rows) == negative_ratio:
                    break

            if len(chosen_rows) == negative_ratio:
                break

        # Fallback should rarely be needed, but keep it robust.
        if len(chosen_rows) < negative_ratio:
            remaining = valid.drop(index=[c.name for c in chosen_rows], errors="ignore").copy()
            remaining["_degree_abs_diff_tmp"] = (
                remaining["drug_degree"].astype(int) - target_degree
            ).abs()
            remaining = remaining.sort_values("_degree_abs_diff_tmp", kind="stable")
            needed = negative_ratio - len(chosen_rows)
            chosen_rows.extend([row for _, row in remaining.head(needed).iterrows()])

        for cand in chosen_rows:
            neg = make_negative_from_graph_present_candidate(
                pos_row=pos_row,
                cand=cand,
                graph_group="graph_present",
                strategy="degree_matched",
                ratio=negative_ratio,
                seed=seed,
                pos_i=pos_i,
            )
            negative_rows.append(neg)

    return pd.DataFrame(negative_rows).reset_index(drop=True)


def sample_graph_unpresent_negatives_normal(pos_df, negative_ratio, seed):
    """
    Fast graph-unpresent / cold-start normal negative sampling:
    - Per disease, valid candidates are cached once.
    - For each positive row, sample negative_ratio candidates without replacement
      from that disease's valid candidate pool.
    """
    rng = np.random.default_rng(seed)
    negative_rows = []

    for pos_i, pos_row in tqdm(
        pos_df.iterrows(),
        total=len(pos_df),
        desc=f"GU normal negatives | ratio={negative_ratio}, seed={seed}",
    ):
        disease_id = str(pos_row["DiseaseID"])
        disease_name = pos_row["DiseaseName"]

        disease_in_primekg = bool(pos_row.get("disease_in_primekg", False))
        disease_node_id = normalize_primekg_node_id(
            pos_row.get("primekg_disease_node_id", pd.NA)
        )

        valid = get_graph_unpresent_valid_candidates_for_disease(
            disease_id=disease_id,
            disease_name=disease_name,
            disease_in_primekg=disease_in_primekg,
            disease_node_id=disease_node_id,
        )

        if len(valid) < negative_ratio:
            raise RuntimeError(
                f"Not enough graph-unpresent valid negative candidates for one positive row. "
                f"pos_i={pos_i}, DiseaseID={disease_id}, DiseaseName={disease_name}, "
                f"available={len(valid)}, required={negative_ratio}, seed={seed}."
            )

        chosen_idx = rng.choice(len(valid), size=negative_ratio, replace=False)

        for idx in chosen_idx:
            cand = valid.iloc[int(idx)]
            neg = make_negative_from_graph_unpresent_candidate(
                pos_row=pos_row,
                cand=cand,
                graph_group="graph_unpresent",
                strategy="normal",
                ratio=negative_ratio,
                seed=seed,
                pos_i=pos_i,
            )
            negative_rows.append(neg)

    return pd.DataFrame(negative_rows).reset_index(drop=True)


def validate_fixed_subset(subset_df):
    """
    Validate one concrete fixed test subset.
    This function intentionally does NOT require global negative-pair uniqueness.
    """
    graph_group = subset_df["graph_group"].iloc[0]
    strategy = subset_df["negative_sampling_strategy"].iloc[0]
    ratio = int(subset_df["negative_ratio"].iloc[0])
    seed = int(subset_df["negative_sampling_seed"].iloc[0])

    positive_rows = int((subset_df["label"] == 1).sum())
    negative_rows = int((subset_df["label"] == 0).sum())

    assert negative_rows == positive_rows * ratio, {
        "graph_group": graph_group,
        "strategy": strategy,
        "ratio": ratio,
        "seed": seed,
        "positive_rows": positive_rows,
        "negative_rows": negative_rows,
    }

    assert set(subset_df["label"].dropna().unique()) == {0, 1}
    assert set(subset_df["sample_type"].dropna().unique()) == {"positive", "negative"}

    neg_df = subset_df[subset_df["label"] == 0].copy()

    # Raw LLM train-source leakage check.
    train_overlap_count = sum(
        is_train_source_overlap(row["DrugID"], row["DiseaseName"])
        for _, row in neg_df.iterrows()
    )
    assert train_overlap_count == 0

    if graph_group == "graph_present":
        neg_df["neg_pair_key"] = list(
            zip(
                neg_df["primekg_drug_node_id"].apply(normalize_primekg_node_id),
                neg_df["primekg_disease_node_id"].apply(normalize_primekg_node_id),
            )
        )

        neg_pairs = set(neg_df["neg_pair_key"])
        assert len(neg_pairs & graph_present_forbidden_graph_pairs) == 0

        # Per-positive uniqueness only.
        dup_count = neg_df.duplicated(
            subset=["positive_row_index", "neg_pair_key"]
        ).sum()
        assert dup_count == 0

    elif graph_group == "graph_unpresent":
        neg_df["neg_original_pair_key"] = list(
            zip(
                neg_df["DrugID"].apply(canonical_drugbank_id),
                neg_df["DiseaseID"].astype(str),
            )
        )
        neg_df["neg_name_pair_key"] = list(
            zip(
                neg_df["DrugID"].apply(canonical_drugbank_id),
                neg_df["DiseaseName"].apply(normalize_text),
            )
        )

        original_pairs = set(neg_df["neg_original_pair_key"])
        name_pairs = set(neg_df["neg_name_pair_key"])

        assert len(original_pairs & graph_unpresent_forbidden_original_pairs) == 0
        assert len(name_pairs & graph_unpresent_forbidden_name_pairs) == 0

        # Per-positive uniqueness only.
        dup_count = neg_df.duplicated(
            subset=["positive_row_index", "neg_name_pair_key"]
        ).sum()
        assert dup_count == 0

    return {
        "positive_rows": positive_rows,
        "negative_rows": negative_rows,
        "total_rows": int(len(subset_df)),
    }


def build_or_load_fixed_subset(graph_group, sampling_strategy, negative_ratio, seed):
    """
    Build one concrete fixed test subset, or load it from disk if available.
    """
    out_path = fixed_test_set_path(
        graph_group=graph_group,
        sampling_strategy=sampling_strategy,
        negative_ratio=negative_ratio,
        seed=seed,
    )

    if out_path.exists() and not OVERWRITE_FIXED_TEST_SETS:
        subset_df = pd.read_csv(out_path)
        source = "loaded"
    else:
        if graph_group == "graph_present" and sampling_strategy == "normal":
            pos_part = make_positive_subset(
                graph_present_pos_base,
                graph_group="graph_present",
                sampling_strategy="normal",
                negative_ratio=negative_ratio,
                seed=seed,
            )
            neg_part = sample_graph_present_negatives_normal(
                graph_present_pos_base,
                negative_ratio=negative_ratio,
                seed=seed,
            )

        elif graph_group == "graph_present" and sampling_strategy == "degree_matched":
            pos_part = make_positive_subset(
                graph_present_pos_base,
                graph_group="graph_present",
                sampling_strategy="degree_matched",
                negative_ratio=negative_ratio,
                seed=seed,
            )
            neg_part = sample_graph_present_negatives_degree_matched(
                graph_present_pos_base,
                negative_ratio=negative_ratio,
                seed=seed,
            )

        elif graph_group == "graph_unpresent" and sampling_strategy == "normal":
            pos_part = make_positive_subset(
                graph_unpresent_pos_base,
                graph_group="graph_unpresent",
                sampling_strategy="normal",
                negative_ratio=negative_ratio,
                seed=seed,
            )
            neg_part = sample_graph_unpresent_negatives_normal(
                graph_unpresent_pos_base,
                negative_ratio=negative_ratio,
                seed=seed,
            )

        else:
            raise ValueError(
                f"Unsupported subset: graph_group={graph_group}, "
                f"sampling_strategy={sampling_strategy}"
            )

        subset_df = pd.concat([pos_part, neg_part], ignore_index=True)
        subset_df = subset_df.sample(frac=1, random_state=seed).reset_index(drop=True)

        # Save immediately for checkpoint / resume.
        subset_df.to_csv(out_path, index=False)
        source = "generated"

    stats = validate_fixed_subset(subset_df)

    degree_abs_diff_mean = pd.NA
    degree_abs_diff_median = pd.NA
    degree_abs_diff_max = pd.NA

    if "degree_abs_diff" in subset_df.columns:
        neg_degree_diff = pd.to_numeric(
            subset_df.loc[subset_df["label"] == 0, "degree_abs_diff"],
            errors="coerce",
        ).dropna()

        if len(neg_degree_diff) > 0:
            degree_abs_diff_mean = float(neg_degree_diff.mean())
            degree_abs_diff_median = float(neg_degree_diff.median())
            degree_abs_diff_max = float(neg_degree_diff.max())

    return subset_df, {
        "dataset": FIXED_TEST_SET_DATASET_NAME,
        "file_name": out_path.name,
        "file_path": str(out_path),
        "source": source,
        "test_config_id": f"ratio{negative_ratio}_seed{seed}",
        "test_subset_id": f"{graph_group}_{sampling_strategy}_ratio{negative_ratio}_seed{seed}",
        "graph_group": graph_group,
        "negative_sampling_strategy": sampling_strategy,
        "negative_ratio": int(negative_ratio),
        "negative_sampling_seed": int(seed),
        "positive_rows": stats["positive_rows"],
        "negative_rows": stats["negative_rows"],
        "total_rows": stats["total_rows"],
        "positive_negative_ratio": f"1:{int(negative_ratio)}",
        "degree_abs_diff_mean": degree_abs_diff_mean,
        "degree_abs_diff_median": degree_abs_diff_median,
        "degree_abs_diff_max": degree_abs_diff_max,
    }


# ------------------------------------------------------------
# 16.4 Generate / load all 45 concrete subsets
# ------------------------------------------------------------

all_test_parts = []
manifest_rows = []

fixed_subset_specs = []

for ratio in NEGATIVE_RATIOS:
    for seed in NEGATIVE_SAMPLING_SEEDS:
        fixed_subset_specs.extend([
            ("graph_present", "normal", ratio, seed),
            ("graph_present", "degree_matched", ratio, seed),
            ("graph_unpresent", "normal", ratio, seed),
        ])

for graph_group, strategy, ratio, seed in fixed_subset_specs:
    print(
        f"\nProcessing subset: dataset={FIXED_TEST_SET_DATASET_NAME}, "
        f"graph_group={graph_group}, strategy={strategy}, ratio=1:{ratio}, seed={seed}"
    )

    subset_df, manifest_row = build_or_load_fixed_subset(
        graph_group=graph_group,
        sampling_strategy=strategy,
        negative_ratio=ratio,
        seed=seed,
    )

    print(
        f"  -> {manifest_row['source']}: {manifest_row['file_name']} "
        f"rows={manifest_row['total_rows']:,} "
        f"pos={manifest_row['positive_rows']:,} "
        f"neg={manifest_row['negative_rows']:,}"
    )

    all_test_parts.append(subset_df)
    manifest_rows.append(manifest_row)


mirage_fixed_test_sets = pd.concat(all_test_parts, ignore_index=True)

fixed_test_set_manifest_df = (
    pd.DataFrame(manifest_rows)
    .sort_values(
        [
            "negative_ratio",
            "negative_sampling_seed",
            "graph_group",
            "negative_sampling_strategy",
        ]
    )
    .reset_index(drop=True)
)

negative_sampling_summary_df = fixed_test_set_manifest_df.copy()

# Save / refresh manifest.
fixed_test_set_manifest_df.to_csv(fixed_test_manifest_path, index=False)

# ------------------------------------------------------------
# 16.5 Overall sanity checks
# ------------------------------------------------------------

print("\nGenerated / loaded fixed negative-sampling test subsets:")
print(f"Ratio × seed configurations: {fixed_test_set_manifest_df['test_config_id'].nunique():,}")
print(f"Concrete test subsets:       {len(fixed_test_set_manifest_df):,}")
print(f"Combined rows in memory:     {len(mirage_fixed_test_sets):,}")
print(f"Manifest CSV:                {fixed_test_manifest_path}")

assert fixed_test_set_manifest_df["test_config_id"].nunique() == expected_test_config_count
assert len(fixed_test_set_manifest_df) == expected_concrete_subset_count
assert fixed_test_set_manifest_df["file_name"].nunique() == expected_concrete_subset_count
assert fixed_test_set_manifest_df["file_path"].nunique() == expected_concrete_subset_count

for _, row in fixed_test_set_manifest_df.iterrows():
    assert row["negative_rows"] == row["positive_rows"] * row["negative_ratio"], row.to_dict()

assert set(mirage_fixed_test_sets["label"].dropna().unique()) == {0, 1}
assert set(mirage_fixed_test_sets["sample_type"].dropna().unique()) == {"positive", "negative"}

print("\nFast checkpoint / resume fixed negative sampling completed successfully.")

print("\nFixed test-set manifest:")
display(fixed_test_set_manifest_df)

print("\nSource counts:")
display(fixed_test_set_manifest_df["source"].value_counts().reset_index(name="count"))

print("\nExample fixed test rows:")
display(
    mirage_fixed_test_sets[
        [
            "test_config_id",
            "test_subset_id",
            "graph_group",
            "negative_sampling_strategy",
            "negative_ratio",
            "negative_sampling_seed",
            "positive_row_index",
            "DrugID",
            "DrugName",
            "DiseaseID",
            "DiseaseName",
            "label",
            "sample_type",
        ]
    ].head(20)
)

Fixed test-set checkpoint directory:
D:\PycharmProjects\TxGNN\data\processed\fixed_test_sets
Overwrite existing subset files: False

Candidate pools after normalization:
Graph-present candidates:   1,408
Graph-unpresent candidates: 1,410

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:1, seed=7
  -> loaded: mirage__graph_present__normal__ratio_1__seed_7.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:1, seed=7
  -> loaded: mirage__graph_present__degree_matched__ratio_1__seed_7.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:1, seed=7
  -> loaded: mirage__graph_unpresent__normal__ratio_1__seed_7.csv rows=38,392 pos=19,196 neg=19,196

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:1, seed=42
  -> loaded: mirage__graph_present__normal__ratio_1__seed_42.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:1, seed=42
  -> loaded: mirage__graph_present__degree_matched__ratio_1__seed_42.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:1, seed=42
  -> loaded: mirage__graph_unpresent__normal__ratio_1__seed_42.csv rows=38,392 pos=19,196 neg=19,196

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:1, seed=999
  -> loaded: mirage__graph_present__normal__ratio_1__seed_999.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:1, seed=999
  -> loaded: mirage__graph_present__degree_matched__ratio_1__seed_999.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:1, seed=999
  -> loaded: mirage__graph_unpresent__normal__ratio_1__seed_999.csv rows=38,392 pos=19,196 neg=19,196

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:1, seed=1443
  -> loaded: mirage__graph_present__normal__ratio_1__seed_1443.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:1, seed=1443
  -> loaded: mirage__graph_present__degree_matched__ratio_1__seed_1443.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:1, seed=1443
  -> loaded: mirage__graph_unpresent__normal__ratio_1__seed_1443.csv rows=38,392 pos=19,196 neg=19,196

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:1, seed=2026
  -> loaded: mirage__graph_present__normal__ratio_1__seed_2026.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:1, seed=2026
  -> loaded: mirage__graph_present__degree_matched__ratio_1__seed_2026.csv rows=39,580 pos=19,790 neg=19,790

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:1, seed=2026
  -> loaded: mirage__graph_unpresent__normal__ratio_1__seed_2026.csv rows=38,392 pos=19,196 neg=19,196

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:4, seed=7
  -> loaded: mirage__graph_present__normal__ratio_4__seed_7.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:4, seed=7
  -> loaded: mirage__graph_present__degree_matched__ratio_4__seed_7.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:4, seed=7
  -> loaded: mirage__graph_unpresent__normal__ratio_4__seed_7.csv rows=95,980 pos=19,196 neg=76,784

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:4, seed=42
  -> loaded: mirage__graph_present__normal__ratio_4__seed_42.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:4, seed=42
  -> loaded: mirage__graph_present__degree_matched__ratio_4__seed_42.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:4, seed=42
  -> loaded: mirage__graph_unpresent__normal__ratio_4__seed_42.csv rows=95,980 pos=19,196 neg=76,784

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:4, seed=999
  -> loaded: mirage__graph_present__normal__ratio_4__seed_999.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:4, seed=999
  -> loaded: mirage__graph_present__degree_matched__ratio_4__seed_999.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:4, seed=999
  -> loaded: mirage__graph_unpresent__normal__ratio_4__seed_999.csv rows=95,980 pos=19,196 neg=76,784

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:4, seed=1443
  -> loaded: mirage__graph_present__normal__ratio_4__seed_1443.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:4, seed=1443
  -> loaded: mirage__graph_present__degree_matched__ratio_4__seed_1443.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:4, seed=1443
  -> loaded: mirage__graph_unpresent__normal__ratio_4__seed_1443.csv rows=95,980 pos=19,196 neg=76,784

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:4, seed=2026
  -> loaded: mirage__graph_present__normal__ratio_4__seed_2026.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:4, seed=2026
  -> loaded: mirage__graph_present__degree_matched__ratio_4__seed_2026.csv rows=98,950 pos=19,790 neg=79,160

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:4, seed=2026
  -> loaded: mirage__graph_unpresent__normal__ratio_4__seed_2026.csv rows=95,980 pos=19,196 neg=76,784

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:9, seed=7
  -> loaded: mirage__graph_present__normal__ratio_9__seed_7.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:9, seed=7
  -> loaded: mirage__graph_present__degree_matched__ratio_9__seed_7.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:9, seed=7
  -> loaded: mirage__graph_unpresent__normal__ratio_9__seed_7.csv rows=191,960 pos=19,196 neg=172,764

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:9, seed=42
  -> loaded: mirage__graph_present__normal__ratio_9__seed_42.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:9, seed=42
  -> loaded: mirage__graph_present__degree_matched__ratio_9__seed_42.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:9, seed=42
  -> loaded: mirage__graph_unpresent__normal__ratio_9__seed_42.csv rows=191,960 pos=19,196 neg=172,764

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:9, seed=999
  -> loaded: mirage__graph_present__normal__ratio_9__seed_999.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:9, seed=999
  -> loaded: mirage__graph_present__degree_matched__ratio_9__seed_999.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:9, seed=999
  -> loaded: mirage__graph_unpresent__normal__ratio_9__seed_999.csv rows=191,960 pos=19,196 neg=172,764

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:9, seed=1443
  -> loaded: mirage__graph_present__normal__ratio_9__seed_1443.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:9, seed=1443
  -> loaded: mirage__graph_present__degree_matched__ratio_9__seed_1443.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:9, seed=1443
  -> loaded: mirage__graph_unpresent__normal__ratio_9__seed_1443.csv rows=191,960 pos=19,196 neg=172,764

Processing subset: dataset=mirage, graph_group=graph_present, strategy=normal, ratio=1:9, seed=2026
  -> loaded: mirage__graph_present__normal__ratio_9__seed_2026.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_present, strategy=degree_matched, ratio=1:9, seed=2026
  -> loaded: mirage__graph_present__degree_matched__ratio_9__seed_2026.csv rows=197,900 pos=19,790 neg=178,110

Processing subset: dataset=mirage, graph_group=graph_unpresent, strategy=normal, ratio=1:9, seed=2026
  -> loaded: mirage__graph_unpresent__normal__ratio_9__seed_2026.csv rows=191,960 pos=19,196 neg=172,764

Generated / loaded fixed negative-sampling test subsets:
Ratio × seed configurations: 15
Concrete test subsets:       45
Combined rows in memory:     4,995,960
Manifest CSV:                ..\data\processed\fixed_test_sets\manifest.csv

Fast checkpoint / resume fixed negative sampling completed successfully.

Fixed test-set manifest:

,dataset,file_name,file_path,source,test_config_id,test_subset_id,graph_group,negative_sampling_strategy,negative_ratio,negative_sampling_seed,positive_rows,negative_rows,total_rows,positive_negative_ratio,degree_abs_diff_mean,degree_abs_diff_median,degree_abs_diff_max
0,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_present_degree_matched_ratio1_seed7,graph_present,degree_matched,1,7,19790,19790,39580,1:1,1.779333,1.0,172.0
1,mirage,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,19790,19790,39580,1:1,747.841637,652.0,2599.0
2,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_unpresent_normal_ratio1_seed7,graph_unpresent,normal,1,7,19196,19196,38392,1:1,<NA>,<NA>,<NA>
3,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed42,graph_present_degree_matched_ratio1_seed42,graph_present,degree_matched,1,42,19790,19790,39580,1:1,1.779333,1.0,172.0
4,mirage,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed42,graph_present_normal_ratio1_seed42,graph_present,normal,1,42,19790,19790,39580,1:1,746.964426,657.0,2599.0
5,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed42,graph_unpresent_normal_ratio1_seed42,graph_unpresent,normal,1,42,19196,19196,38392,1:1,<NA>,<NA>,<NA>
6,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed999,graph_present_degree_matched_ratio1_seed999,graph_present,degree_matched,1,999,19790,19790,39580,1:1,1.779333,1.0,172.0
7,mirage,mirage__graph_present__normal__ratio_1__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed999,graph_present_normal_ratio1_seed999,graph_present,normal,1,999,19790,19790,39580,1:1,745.732693,657.0,2588.0
8,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed999,graph_unpresent_normal_ratio1_seed999,graph_unpresent,normal,1,999,19196,19196,38392,1:1,<NA>,<NA>,<NA>
9,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed1443,graph_present_degree_matched_ratio1_seed1443,graph_present,degree_matched,1,1443,19790,19790,39580,1:1,1.779333,1.0,172.0
10,mirage,mirage__graph_present__normal__ratio_1__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed1443,graph_present_normal_ratio1_seed1443,graph_present,normal,1,1443,19790,19790,39580,1:1,749.436331,663.0,2597.0
11,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed1443,graph_unpresent_normal_ratio1_seed1443,graph_unpresent,normal,1,1443,19196,19196,38392,1:1,<NA>,<NA>,<NA>
12,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed2026,graph_present_degree_matched_ratio1_seed2026,graph_present,degree_matched,1,2026,19790,19790,39580,1:1,1.779333,1.0,172.0
13,mirage,mirage__graph_present__normal__ratio_1__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed2026,graph_present_normal_ratio1_seed2026,graph_present,normal,1,2026,19790,19790,39580,1:1,758.031076,670.0,2599.0
14,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed2026,graph_unpresent_normal_ratio1_seed2026,graph_unpresent,normal,1,2026,19196,19196,38392,1:1,<NA>,<NA>,<NA>
15,mirage,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed7,graph_present_degree_matched_ratio4_seed7,graph_present,degree_matched,4,7,19790,79160,98950,1:4,4.710258,2.0,384.0
16,mirage,mirage__graph_present__normal__ratio_4__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed7,graph_present_normal_ratio4_seed7,graph_present,normal,4,7,19790,79160,98950,1:4,750.606038,661.0,2599.0
17,mirage,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed7,graph_unpresent_normal_ratio4_seed7,graph_unpresent,normal,4,7,19196,76784,95980,1:4,<NA>,<NA>,<NA>
18,mirage,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed42,graph_present_degree_matched_ratio4_seed42,graph_present,degree_matched,4,42,19790,79160,98950,1:4,4.710258,2.0,384.0
19,mirage,mirage__graph_present__normal__ratio_4__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed42,graph_present_normal_ratio4_seed42,graph_present,normal,4,42,19790,79160,98950,1:4,750.609803,661.0,2599.0
20,mirage,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed42,graph_unpresent_normal_ratio4_seed42,graph_unpresent,normal,4,42,19196,76784,95980,1:4,<NA>,<NA>,<NA>
21,mirage,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed999,graph_present_degree_matched_ratio4_seed999,graph_present,degree_matched,4,999,19790,79160,98950,1:4,4.710258,2.0,384.0
22,mirage,mirage__graph_present__normal__ratio_4__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed999,graph_present_normal_ratio4_seed999,graph_present,normal,4,999,19790,79160,98950,1:4,751.526011,661.0,2599.0
23,mirage,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed999,graph_unpresent_normal_ratio4_seed999,graph_unpresent,normal,4,999,19196,76784,95980,1:4,<NA>,<NA>,<NA>
24,mirage,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed1443,graph_present_degree_matched_ratio4_seed1443,graph_present,degree_matched,4,1443,19790,79160,98950,1:4,4.710258,2.0,384.0
25,mirage,mirage__graph_present__normal__ratio_4__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed1443,graph_present_normal_ratio4_seed1443,graph_present,normal,4,1443,19790,79160,98950,1:4,748.492067,659.0,2599.0
26,mirage,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed1443,graph_unpresent_normal_ratio4_seed1443,graph_unpresent,normal,4,1443,19196,76784,95980,1:4,<NA>,<NA>,<NA>
27,mirage,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed2026,graph_present_degree_matched_ratio4_seed2026,graph_present,degree_matched,4,2026,19790,79160,98950,1:4,4.710258,2.0,384.0
28,mirage,mirage__graph_present__normal__ratio_4__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed2026,graph_present_normal_ratio4_seed2026,graph_present,normal,4,2026,19790,79160,98950,1:4,749.791587,656.0,2599.0
29,mirage,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio4_seed2026,graph_unpresent_normal_ratio4_seed2026,graph_unpresent,normal,4,2026,19196,76784,95980,1:4,<NA>,<NA>,<NA>
30,mirage,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed7,graph_present_degree_matched_ratio9_seed7,graph_present,degree_matched,9,7,19790,178110,197900,1:9,9.109943,4.0,481.0
31,mirage,mirage__graph_present__normal__ratio_9__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed7,graph_present_normal_ratio9_seed7,graph_present,normal,9,7,19790,178110,197900,1:9,751.550087,662.0,2599.0
32,mirage,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed7,graph_unpresent_normal_ratio9_seed7,graph_unpresent,normal,9,7,19196,172764,191960,1:9,<NA>,<NA>,<NA>
33,mirage,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed42,graph_present_degree_matched_ratio9_seed42,graph_present,degree_matched,9,42,19790,178110,197900,1:9,9.109943,4.0,481.0
34,mirage,mirage__graph_present__normal__ratio_9__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed42,graph_present_normal_ratio9_seed42,graph_present,normal,9,42,19790,178110,197900,1:9,750.196339,656.5,2599.0
35,mirage,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed42,graph_unpresent_normal_ratio9_seed42,graph_unpresent,normal,9,42,19196,172764,191960,1:9,<NA>,<NA>,<NA>
36,mirage,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed999,graph_present_degree_matched_ratio9_seed999,graph_present,degree_matched,9,999,19790,178110,197900,1:9,9.109943,4.0,481.0
37,mirage,mirage__graph_present__normal__ratio_9__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed999,graph_present_normal_ratio9_seed999,graph_present,normal,9,999,19790,178110,197900,1:9,752.544158,663.0,2599.0
38,mirage,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed999,graph_unpresent_normal_ratio9_seed999,graph_unpresent,normal,9,999,19196,172764,191960,1:9,<NA>,<NA>,<NA>
39,mirage,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed1443,graph_present_degree_matched_ratio9_seed1443,graph_present,degree_matched,9,1443,19790,178110,197900,1:9,9.109943,4.0,481.0
40,mirage,mirage__graph_present__normal__ratio_9__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed1443,graph_present_normal_ratio9_seed1443,graph_present,normal,9,1443,19790,178110,197900,1:9,751.497861,659.0,2599.0
41,mirage,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed1443,graph_unpresent_normal_ratio9_seed1443,graph_unpresent,normal,9,1443,19196,172764,191960,1:9,<NA>,<NA>,<NA>
42,mirage,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed2026,graph_present_degree_matched_ratio9_seed2026,graph_present,degree_matched,9,2026,19790,178110,197900,1:9,9.109943,4.0,481.0
43,mirage,mirage__graph_present__normal__ratio_9__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed2026,graph_present_normal_ratio9_seed2026,graph_present,normal,9,2026,19790,178110,197900,1:9,752.862445,661.0,2599.0
44,mirage,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio9_seed2026,graph_unpresent_normal_ratio9_seed2026,graph_unpresent,normal,9,2026,19196,172764,191960,1:9,<NA>,<NA>,<NA>

Source counts:

   source  count
0  loaded     45

Example fixed test rows:

,test_config_id,test_subset_id,graph_group,negative_sampling_strategy,negative_ratio,negative_sampling_seed,positive_row_index,DrugID,DrugName,DiseaseID,DiseaseName,label,sample_type
0,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,2257,DB01170,Guanethidine,MESH:D001943,Breast Neoplasms,0,negative
1,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,3776,DB00773,Etoposide,MESH:D003329,Coronary Vasospasm,1,positive
2,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,14603,DB00927,Famotidine,MESH:D013262,Stevens-Johnson Syndrome,1,positive
3,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,19352,DB08882,Linagliptin,MESH:D056486,Chemical and Drug Induced Liver Injury,0,negative
4,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,7287,DB00899,Remifentanil,MESH:D006973,Hypertension,1,positive
5,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,143,DB00578,Carbenicillin,MESH:D000163,Acquired Immunodeficiency Syndrome,0,negative
6,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,12671,DB02342,2-Methoxyestradiol,MESH:D011605,"Psychoses, Substance-Induced",0,negative
7,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,12396,DB09070,Tibolone,MESH:D011507,Proteinuria,0,negative
8,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,1368,DB00370,Mirtazapine,MESH:D001321,Autistic Disorder,1,positive
9,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,16467,DB00979,Cyclopentolate,MESH:D016137,Spina Bifida Cystica,0,negative
10,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,6245,DB00535,Cefdinir,MESH:D006333,Heart Failure,0,negative
11,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,3021,DB01014,Balsalazide,MESH:D002546,"Ischemic Attack, Transient",0,negative
12,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,7331,DB09285,Morniflumate,MESH:D006973,Hypertension,0,negative
13,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,18547,DB01169,Arsenic trioxide,MESH:D051437,Renal Insufficiency,1,positive
14,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,3710,DB01029,Irbesartan,MESH:D003324,Coronary Artery Disease,0,negative
15,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,3912,DB00907,Cocaine,MESH:D003639,"Hearing Loss, Sudden",1,positive
16,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,3332,DB00833,Cefaclor,MESH:D002780,"Cholestasis, Intrahepatic",0,negative
17,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,11531,DB00762,Irinotecan,MESH:D010190,Pancreatic Neoplasms,1,positive
18,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,14782,DB03701,Vanoxerine,MESH:D013262,Stevens-Johnson Syndrome,0,negative
19,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,439,DB06589,Pazopanib,MESH:D000707,Anaphylaxis,0,negative

In [17]:
# ============================================================
# 17. Convert fixed test sets to GNN and LLM evaluation formats
# ============================================================
# Input:
#   OUTPUT_DIR / "fixed_test_sets"/*.csv
#
# Output:
#   OUTPUT_DIR / "fixed_test_sets_gnn"/*.csv
#       graph_present only: 30 files
#       columns:
#           x_type,x_id,relation,y_type,y_id,x_idx,y_idx,label
#
#   OUTPUT_DIR / "fixed_test_sets_llm"/*.csv
#       graph_present + graph_unpresent: 45 files
#       columns:
#           relation,x_name,y_name,label,x_type,y_type,x_index,y_index
#
# Notes:
# - LLM format keeps x=drug, y=disease.
# - GNN format keeps x=drug, y=disease and includes type/id/idx/relation.
# - Both formats keep label because these fixed test sets contain positives
#   and pre-sampled negatives.

# ------------------------------------------------------------
# 17.0 Output directories and manifest paths
# ------------------------------------------------------------

FIXED_TEST_SET_DIR = OUTPUT_DIR / "fixed_test_sets"
GNN_TEST_SET_DIR = OUTPUT_DIR / "fixed_test_sets_gnn"
LLM_TEST_SET_DIR = OUTPUT_DIR / "fixed_test_sets_llm"

GNN_TEST_SET_DIR.mkdir(parents=True, exist_ok=True)
LLM_TEST_SET_DIR.mkdir(parents=True, exist_ok=True)

fixed_test_manifest_path = FIXED_TEST_SET_DIR / "manifest.csv"
gnn_manifest_path = GNN_TEST_SET_DIR / "manifest.csv"
llm_manifest_path = LLM_TEST_SET_DIR / "manifest.csv"

assert fixed_test_manifest_path.exists(), f"Manifest not found: {fixed_test_manifest_path}"

fixed_manifest = pd.read_csv(fixed_test_manifest_path)

print("Loaded fixed test-set manifest:")
print(f"- Manifest: {fixed_test_manifest_path}")
print(f"- Rows:     {len(fixed_manifest):,}")
display(fixed_manifest.head())


# ------------------------------------------------------------
# 17.1 Conversion helpers
# ------------------------------------------------------------

def convert_to_gnn_format(df):
    """
    Convert one graph-present fixed test set to GNN edge format.

    Expected semantic direction:
        x = drug
        y = disease

    Output columns:
        x_type,x_id,relation,y_type,y_id,x_idx,y_idx,label
    """
    required_cols = {
        "primekg_drug_node_id",
        "primekg_disease_node_id",
        "txgnn_drug_idx",
        "txgnn_disease_idx",
        "label",
    }
    missing = required_cols - set(df.columns)
    assert not missing, f"GNN conversion missing columns: {missing}"

    out = pd.DataFrame({
        "x_type": ["drug"] * len(df),
        "x_id": df["primekg_drug_node_id"].apply(normalize_primekg_node_id),
        "relation": [DEFAULT_EXTERNAL_RELATION] * len(df),
        "y_type": ["disease"] * len(df),
        "y_id": df["primekg_disease_node_id"].apply(normalize_primekg_node_id),
        "x_idx": pd.to_numeric(df["txgnn_drug_idx"], errors="raise").astype(int),
        "y_idx": pd.to_numeric(df["txgnn_disease_idx"], errors="raise").astype(int),
        "label": pd.to_numeric(df["label"], errors="raise").astype(int),
    })

    # Strict checks
    assert out["x_type"].eq("drug").all()
    assert out["y_type"].eq("disease").all()
    assert out["x_id"].notna().all()
    assert out["y_id"].notna().all()
    assert out["x_idx"].notna().all()
    assert out["y_idx"].notna().all()
    assert set(out["label"].unique()) == {0, 1}

    return out


def convert_to_llm_format(df):
    """
    Convert one fixed test set to LLM evaluation format.

    Expected semantic direction:
        x = drug
        y = disease

    Output columns:
        relation,x_name,y_name,label,x_type,y_type,x_index,y_index
    """
    required_cols = {
        "DrugName",
        "DiseaseName",
        "label",
    }
    missing = required_cols - set(df.columns)
    assert not missing, f"LLM conversion missing columns: {missing}"

    # For LLM evaluation:
    # - x_index/y_index are optional helper fields.
    # - graph_unpresent rows may have missing node indices.
    # - graph_present rows should usually have valid PrimeKG or TxGNN indices.

    if "primekg_drug_node_index" in df.columns:
        x_index = pd.to_numeric(df["primekg_drug_node_index"], errors="coerce").astype("Int64")
    elif "txgnn_drug_idx" in df.columns:
        x_index = pd.to_numeric(df["txgnn_drug_idx"], errors="coerce").astype("Int64")
    else:
        x_index = pd.Series([pd.NA] * len(df), dtype="Int64")

    if "primekg_disease_node_index" in df.columns:
        y_index = pd.to_numeric(df["primekg_disease_node_index"], errors="coerce").astype("Int64")
    elif "txgnn_disease_idx" in df.columns:
        y_index = pd.to_numeric(df["txgnn_disease_idx"], errors="coerce").astype("Int64")
    else:
        y_index = pd.Series([pd.NA] * len(df), dtype="Int64")

    out = pd.DataFrame({
        "relation": [DEFAULT_EXTERNAL_RELATION] * len(df),
        "x_name": df["DrugName"].astype(str),
        "y_name": df["DiseaseName"].astype(str),
        "label": pd.to_numeric(df["label"], errors="raise").astype(int),
        "x_type": ["drug"] * len(df),
        "y_type": ["disease"] * len(df),
        "x_index": x_index,
        "y_index": y_index,
    })

    # Strict checks
    assert out["x_type"].eq("drug").all()
    assert out["y_type"].eq("disease").all()
    assert out["x_name"].notna().all()
    assert out["y_name"].notna().all()
    assert out["x_name"].astype(str).str.len().gt(0).all()
    assert out["y_name"].astype(str).str.len().gt(0).all()
    assert set(out["label"].unique()) == {0, 1}

    return out


def converted_file_name(original_file_name, suffix):
    """
    Keep original naming and add conversion suffix before .csv.
    """
    stem = Path(original_file_name).stem
    return f"{stem}__{suffix}.csv"


def resolve_source_path(row):
    """
    Resolve source fixed test-set path robustly.
    Manifest file_path may point to another machine path; fallback to local dir.
    """
    src_path = Path(row["file_path"])

    if not src_path.exists():
        src_path = FIXED_TEST_SET_DIR / row["file_name"]

    assert src_path.exists(), f"Source fixed test set not found: {src_path}"
    return src_path


# ------------------------------------------------------------
# 17.2 Convert all 45 fixed test sets for LLM
# ------------------------------------------------------------

llm_manifest_rows = []

for _, row in tqdm(
    fixed_manifest.iterrows(),
    total=len(fixed_manifest),
    desc="Converting fixed test sets to LLM format",
):
    src_path = resolve_source_path(row)

    df = pd.read_csv(src_path)
    llm_df = convert_to_llm_format(df)

    out_name = converted_file_name(row["file_name"], suffix="llm")
    out_path = LLM_TEST_SET_DIR / out_name

    llm_df.to_csv(out_path, index=False)

    llm_manifest_rows.append({
        "source_file_name": row["file_name"],
        "source_file_path": str(src_path),
        "converted_file_name": out_name,
        "converted_file_path": str(out_path),
        "format": "llm",
        "graph_group": row["graph_group"],
        "negative_sampling_strategy": row["negative_sampling_strategy"],
        "negative_ratio": int(row["negative_ratio"]),
        "negative_sampling_seed": int(row["negative_sampling_seed"]),
        "positive_rows": int((llm_df["label"] == 1).sum()),
        "negative_rows": int((llm_df["label"] == 0).sum()),
        "total_rows": int(len(llm_df)),
    })

llm_manifest_df = (
    pd.DataFrame(llm_manifest_rows)
    .sort_values(
        [
            "negative_ratio",
            "negative_sampling_seed",
            "graph_group",
            "negative_sampling_strategy",
        ]
    )
    .reset_index(drop=True)
)

llm_manifest_df.to_csv(llm_manifest_path, index=False)


# ------------------------------------------------------------
# 17.3 Convert graph-present 30 fixed test sets for GNN
# ------------------------------------------------------------

gnn_manifest_rows = []

gnn_source_manifest = fixed_manifest[
    fixed_manifest["graph_group"] == "graph_present"
].copy()

for _, row in tqdm(
    gnn_source_manifest.iterrows(),
    total=len(gnn_source_manifest),
    desc="Converting graph-present fixed test sets to GNN format",
):
    src_path = resolve_source_path(row)

    df = pd.read_csv(src_path)
    gnn_df = convert_to_gnn_format(df)

    out_name = converted_file_name(row["file_name"], suffix="gnn")
    out_path = GNN_TEST_SET_DIR / out_name

    gnn_df.to_csv(out_path, index=False)

    gnn_manifest_rows.append({
        "source_file_name": row["file_name"],
        "source_file_path": str(src_path),
        "converted_file_name": out_name,
        "converted_file_path": str(out_path),
        "format": "gnn",
        "graph_group": row["graph_group"],
        "negative_sampling_strategy": row["negative_sampling_strategy"],
        "negative_ratio": int(row["negative_ratio"]),
        "negative_sampling_seed": int(row["negative_sampling_seed"]),
        "positive_rows": int((gnn_df["label"] == 1).sum()),
        "negative_rows": int((gnn_df["label"] == 0).sum()),
        "total_rows": int(len(gnn_df)),
    })

gnn_manifest_df = (
    pd.DataFrame(gnn_manifest_rows)
    .sort_values(
        [
            "negative_ratio",
            "negative_sampling_seed",
            "graph_group",
            "negative_sampling_strategy",
        ]
    )
    .reset_index(drop=True)
)

gnn_manifest_df.to_csv(gnn_manifest_path, index=False)


# ------------------------------------------------------------
# 17.4 Update summary.json
# ------------------------------------------------------------

summary_json_path = OUTPUT_DIR / "summary.json"

if summary_json_path.exists():
    with open(summary_json_path, "r", encoding="utf-8") as f:
        summary = json.load(f)
else:
    summary = {}

summary.update({
    "converted_test_sets": {
        "llm": {
            "directory": str(LLM_TEST_SET_DIR),
            "manifest_csv": str(llm_manifest_path),
            "file_count": int(len(llm_manifest_df)),
            "expected_file_count": 45,
            "columns": [
                "relation",
                "x_name",
                "y_name",
                "label",
                "x_type",
                "y_type",
                "x_index",
                "y_index",
            ],
            "scope": "all fixed test sets: graph_present and graph_unpresent",
            "semantic_direction": "x is always drug; y is always disease",
        },
        "gnn": {
            "directory": str(GNN_TEST_SET_DIR),
            "manifest_csv": str(gnn_manifest_path),
            "file_count": int(len(gnn_manifest_df)),
            "expected_file_count": 30,
            "columns": [
                "x_type",
                "x_id",
                "relation",
                "y_type",
                "y_id",
                "x_idx",
                "y_idx",
                "label",
            ],
            "scope": "graph_present fixed test sets only",
            "semantic_direction": "x is always drug; y is always disease",
            "note": (
                "GNN files include label because fixed test sets contain both positive "
                "and pre-sampled negative edges. If a downstream TxGNN function only "
                "accepts edge columns, keep label separately and pass only the first "
                "seven edge columns for prediction."
            ),
        },
    }
})

with open(summary_json_path, "w", encoding="utf-8") as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)


# ------------------------------------------------------------
# 17.5 Sanity checks and report
# ------------------------------------------------------------

assert len(llm_manifest_df) == 45, f"Expected 45 LLM files, got {len(llm_manifest_df)}"
assert len(gnn_manifest_df) == 30, f"Expected 30 GNN files, got {len(gnn_manifest_df)}"

assert llm_manifest_df["converted_file_name"].nunique() == 45
assert gnn_manifest_df["converted_file_name"].nunique() == 30

for _, row in llm_manifest_df.iterrows():
    assert row["negative_rows"] == row["positive_rows"] * row["negative_ratio"], row.to_dict()

for _, row in gnn_manifest_df.iterrows():
    assert row["negative_rows"] == row["positive_rows"] * row["negative_ratio"], row.to_dict()

print("Converted fixed test sets:")
print(f"- LLM output directory: {LLM_TEST_SET_DIR}")
print(f"- LLM manifest:         {llm_manifest_path}")
print(f"- LLM files:            {len(llm_manifest_df)}")

print(f"\n- GNN output directory: {GNN_TEST_SET_DIR}")
print(f"- GNN manifest:         {gnn_manifest_path}")
print(f"- GNN files:            {len(gnn_manifest_df)}")

print(f"\n- Updated summary JSON: {summary_json_path}")

print("\nLLM manifest:")
display(llm_manifest_df)

print("\nGNN manifest:")
display(gnn_manifest_df)

print("\nExample LLM file:")
example_llm_path = Path(llm_manifest_df.iloc[0]["converted_file_path"])
display(pd.read_csv(example_llm_path).head())

print("\nExample GNN file:")
example_gnn_path = Path(gnn_manifest_df.iloc[0]["converted_file_path"])
display(pd.read_csv(example_gnn_path).head())

Loaded fixed test-set manifest:
- Manifest: ..\data\processed\fixed_test_sets\manifest.csv
- Rows:     45

,dataset,file_name,file_path,source,test_config_id,test_subset_id,graph_group,negative_sampling_strategy,negative_ratio,negative_sampling_seed,positive_rows,negative_rows,total_rows,positive_negative_ratio,degree_abs_diff_mean,degree_abs_diff_median,degree_abs_diff_max
0,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_present_degree_matched_ratio1_seed7,graph_present,degree_matched,1,7,19790,19790,39580,1:1,1.779333,1.0,172.0
1,mirage,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_present_normal_ratio1_seed7,graph_present,normal,1,7,19790,19790,39580,1:1,747.841637,652.0,2599.0
2,mirage,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed7,graph_unpresent_normal_ratio1_seed7,graph_unpresent,normal,1,7,19196,19196,38392,1:1,NaN,NaN,NaN
3,mirage,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed42,graph_present_degree_matched_ratio1_seed42,graph_present,degree_matched,1,42,19790,19790,39580,1:1,1.779333,1.0,172.0
4,mirage,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,loaded,ratio1_seed42,graph_present_normal_ratio1_seed42,graph_present,normal,1,42,19790,19790,39580,1:1,746.964426,657.0,2599.0

Converting fixed test sets to LLM format:   0%|          | 0/45 [00:00<?, ?it/s]

Converting graph-present fixed test sets to GNN format:   0%|          | 0/30 [00:00<?, ?it/s]

Converted fixed test sets:
- LLM output directory: ..\data\processed\fixed_test_sets_llm
- LLM manifest:         ..\data\processed\fixed_test_sets_llm\manifest.csv
- LLM files:            45

- GNN output directory: ..\data\processed\fixed_test_sets_gnn
- GNN manifest:         ..\data\processed\fixed_test_sets_gnn\manifest.csv
- GNN files:            30

- Updated summary JSON: ..\data\processed\summary.json

LLM manifest:

,source_file_name,source_file_path,converted_file_name,converted_file_path,format,graph_group,negative_sampling_strategy,negative_ratio,negative_sampling_seed,positive_rows,negative_rows,total_rows
0,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,1,7,19790,19790,39580
1,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,1,7,19790,19790,39580
2,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,1,7,19196,19196,38392
3,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,1,42,19790,19790,39580
4,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,1,42,19790,19790,39580
5,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,1,42,19196,19196,38392
6,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,1,999,19790,19790,39580
7,mirage__graph_present__normal__ratio_1__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,1,999,19790,19790,39580
8,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,1,999,19196,19196,38392
9,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,1,1443,19790,19790,39580
10,mirage__graph_present__normal__ratio_1__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,1,1443,19790,19790,39580
11,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,1,1443,19196,19196,38392
12,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,1,2026,19790,19790,39580
13,mirage__graph_present__normal__ratio_1__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_2...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,1,2026,19790,19790,39580
14,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_1__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,1,2026,19196,19196,38392
15,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,4,7,19790,79160,98950
16,mirage__graph_present__normal__ratio_4__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_7...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,4,7,19790,79160,98950
17,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,4,7,19196,76784,95980
18,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,4,42,19790,79160,98950
19,mirage__graph_present__normal__ratio_4__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,4,42,19790,79160,98950
20,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,4,42,19196,76784,95980
21,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,4,999,19790,79160,98950
22,mirage__graph_present__normal__ratio_4__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,4,999,19790,79160,98950
23,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,4,999,19196,76784,95980
24,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,4,1443,19790,79160,98950
25,mirage__graph_present__normal__ratio_4__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,4,1443,19790,79160,98950
26,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,4,1443,19196,76784,95980
27,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,4,2026,19790,79160,98950
28,mirage__graph_present__normal__ratio_4__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_2...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,4,2026,19790,79160,98950
29,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_4__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,4,2026,19196,76784,95980
30,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,9,7,19790,178110,197900
31,mirage__graph_present__normal__ratio_9__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_7...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,9,7,19790,178110,197900
32,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,9,7,19196,172764,191960
33,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,9,42,19790,178110,197900
34,mirage__graph_present__normal__ratio_9__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_4...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,9,42,19790,178110,197900
35,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,9,42,19196,172764,191960
36,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,9,999,19790,178110,197900
37,mirage__graph_present__normal__ratio_9__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,9,999,19790,178110,197900
38,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,9,999,19196,172764,191960
39,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,9,1443,19790,178110,197900
40,mirage__graph_present__normal__ratio_9__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_1...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,9,1443,19790,178110,197900
41,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,9,1443,19196,172764,191960
42,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,degree_matched,9,2026,19790,178110,197900
43,mirage__graph_present__normal__ratio_9__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_2...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_present,normal,9,2026,19790,178110,197900
44,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_unpresent__normal__ratio_9__seed...,..\data\processed\fixed_test_sets_llm\mirage__...,llm,graph_unpresent,normal,9,2026,19196,172764,191960

GNN manifest:

,source_file_name,source_file_path,converted_file_name,converted_file_path,format,graph_group,negative_sampling_strategy,negative_ratio,negative_sampling_seed,positive_rows,negative_rows,total_rows
0,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,1,7,19790,19790,39580
1,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_7...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,1,7,19790,19790,39580
2,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,1,42,19790,19790,39580
3,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,1,42,19790,19790,39580
4,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,1,999,19790,19790,39580
5,mirage__graph_present__normal__ratio_1__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,1,999,19790,19790,39580
6,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,1,1443,19790,19790,39580
7,mirage__graph_present__normal__ratio_1__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,1,1443,19790,19790,39580
8,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,1,2026,19790,19790,39580
9,mirage__graph_present__normal__ratio_1__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_1__seed_2...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,1,2026,19790,19790,39580
10,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,4,7,19790,79160,98950
11,mirage__graph_present__normal__ratio_4__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_7...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,4,7,19790,79160,98950
12,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,4,42,19790,79160,98950
13,mirage__graph_present__normal__ratio_4__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,4,42,19790,79160,98950
14,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,4,999,19790,79160,98950
15,mirage__graph_present__normal__ratio_4__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,4,999,19790,79160,98950
16,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,4,1443,19790,79160,98950
17,mirage__graph_present__normal__ratio_4__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,4,1443,19790,79160,98950
18,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,4,2026,19790,79160,98950
19,mirage__graph_present__normal__ratio_4__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_4__seed_2...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,4,2026,19790,79160,98950
20,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,9,7,19790,178110,197900
21,mirage__graph_present__normal__ratio_9__seed_7...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_7...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,9,7,19790,178110,197900
22,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,9,42,19790,178110,197900
23,mirage__graph_present__normal__ratio_9__seed_4...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_4...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,9,42,19790,178110,197900
24,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,9,999,19790,178110,197900
25,mirage__graph_present__normal__ratio_9__seed_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,9,999,19790,178110,197900
26,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,9,1443,19790,178110,197900
27,mirage__graph_present__normal__ratio_9__seed_1...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_1...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,9,1443,19790,178110,197900
28,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__degree_matched__ratio_9...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,degree_matched,9,2026,19790,178110,197900
29,mirage__graph_present__normal__ratio_9__seed_2...,..\data\processed\fixed_test_sets\mirage__grap...,mirage__graph_present__normal__ratio_9__seed_2...,..\data\processed\fixed_test_sets_gnn\mirage__...,gnn,graph_present,normal,9,2026,19790,178110,197900

Example LLM file:

,relation,x_name,y_name,label,x_type,y_type,x_index,y_index
0,indication,Valproic acid,Breast Neoplasms,0,drug,disease,15982,35771
1,indication,Etoposide,Coronary Vasospasm,1,drug,disease,14604,37894
2,indication,Famotidine,Stevens-Johnson Syndrome,1,drug,disease,15316,32746
3,indication,Bopindolol,Chemical and Drug Induced Liver Injury,0,drug,disease,14063,36544
4,indication,Remifentanil,Hypertension,1,drug,disease,17152,33577

Example GNN file:

  x_type     x_id    relation   y_type   y_id  x_idx  y_idx  label
0   drug  DB00313  indication  disease  21100    301   7875      0
1   drug  DB00773  indication  disease   5356    755  12942      1
2   drug  DB00927  indication  disease  18229    908   5711      1
3   drug  DB08807  indication  disease   5359   5541  12944      0
4   drug  DB00899  indication  disease   5044    880  12675      1